from flask import Flask, render_template_string

app = Flask(__name__)

HTML = r'''<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Электрический склад</title>
<style>
*{box-sizing:border-box}:root{--bg:#eef2f3;--panel:#f8faf9;--ink:#34454b;--muted:#718087;--line:#ccd7d8;--accent:#527d83;--soft:#e0ebea;--warn:#8a6d3b}
body{margin:0;font-family:Arial,Helvetica,sans-serif;background:var(--bg);color:var(--ink)}
header{background:#536a70;color:#f8fbfb;padding:14px 20px}.top{max-width:1250px;margin:auto;display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}h1{margin:0;font-size:25px}.top-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.lang button,.owner-btn,.back,.save,.edit-btn,.modal-btn,.file-btn{border:1px solid var(--line);border-radius:8px;padding:8px 11px;cursor:pointer}.owner-btn{background:#eef5f3;color:#30494f;font-weight:700}.owner-btn.unlocked{background:#d9efe6}
.workspace{max-width:1250px;margin:auto;padding:18px 14px;display:grid;grid-template-columns:145px 1fr;gap:18px}.side{display:flex;flex-direction:column;align-items:center;gap:12px}.diamond-button{width:112px;height:112px;border:0;background:transparent;cursor:pointer}.diamond{width:80px;height:80px;margin:16px auto;background:#f7faf9;border:2px solid var(--line);border-radius:13px;transform:rotate(45deg);display:flex;align-items:center;justify-content:center}.diamond-inner{width:102px;transform:rotate(-45deg);text-align:center;font-weight:700;font-size:13px;overflow-wrap:anywhere}.icon{display:block;font-size:20px}.content{background:var(--panel);border:1px solid var(--line);border-radius:15px;padding:22px;min-width:0}.page{display:none}.page.active{display:block}.subtitle{color:var(--muted)}.box{border:1px solid var(--line);border-radius:12px;padding:20px;background:#fff;min-height:350px}
.machine-grid,.section-grid{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:12px}.tile-wrap{position:relative}.machine,.section-tile,.detail-tile,.fault-main{width:100%;min-height:78px;border:1px solid var(--line);border-radius:10px;background:#f2f6f5;color:var(--ink);font-weight:700;cursor:pointer;padding:12px 10px;font-size:14px;line-height:1.18;overflow-wrap:anywhere;white-space:normal}.machine:hover,.section-tile:hover,.detail-tile:hover,.fault-main:hover{background:var(--soft);border-color:var(--accent)}.edit-btn{display:none;position:absolute;top:5px;right:5px;padding:3px 7px;font-size:12px;background:#fff;z-index:3}.owner-mode .edit-btn{display:block}.fault-main{width:220px;min-height:82px;margin:4px 0 20px;background:#e8f1ef;font-size:16px}.detail-grid{display:grid;grid-template-columns:repeat(2,minmax(180px,1fr));gap:16px;max-width:620px}.detail-tile{min-height:110px}.section-info{margin-top:18px;padding:16px;border:1px solid var(--line);border-radius:12px;background:#fff}.fault-form{margin-top:18px;padding:16px;border:1px solid var(--line);border-radius:12px;background:#fff}.fault-form label{display:block;font-weight:700;margin:12px 0 5px}.fault-form input:not([type=file]),.fault-form textarea,.fault-form select{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;background:#fbfdfc}.fault-form textarea{min-height:70px}.save{margin-top:14px;background:var(--accent);color:white;font-weight:700}.records{margin-top:18px;display:grid;gap:10px}.record{background:#fff;border:1px solid var(--line);border-radius:10px;padding:12px}.record img{max-width:180px;max-height:130px;border-radius:8px;margin-top:8px}.record-date{font-weight:700}.stats{margin:15px 0;padding:10px;background:var(--soft);border-radius:8px;font-weight:700}.file-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:6px 0 3px}.native-file{position:absolute;width:1px;height:1px;opacity:0;pointer-events:none}.file-btn{display:inline-block;background:#eef5f3;color:var(--ink);font-weight:700}.file-name{font-size:13px;color:var(--muted);overflow-wrap:anywhere}.file-formats{font-size:12px;color:var(--muted);margin:2px 0 10px}.record-doc{display:inline-block;margin-top:8px;color:var(--accent);font-weight:700}
.modal{display:none;position:fixed;inset:0;background:#0006;z-index:20;align-items:center;justify-content:center;padding:18px}.modal.open{display:flex}.modal-card{width:min(520px,100%);background:#fff;border-radius:14px;padding:20px;box-shadow:0 15px 50px #0004}.modal-card h3{margin-top:0}.modal-card label{display:block;font-weight:700;margin:10px 0 4px}.modal-card input{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px}.modal-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:15px;flex-wrap:wrap}.modal-btn.primary{background:var(--accent);color:white}.hint{font-size:12px;color:var(--muted);margin-top:8px}.security-note{font-size:12px;color:var(--warn);margin-top:8px}
@media(max-width:720px){.workspace{grid-template-columns:105px 1fr;gap:8px;padding:10px 6px}.diamond-button{width:92px;height:92px}.diamond{width:64px;height:64px}.diamond-inner{width:86px;font-size:11px}.content{padding:14px 10px}.machine-grid,.section-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.machine,.section-tile{min-height:70px;font-size:12px;padding:9px 7px}.detail-grid{grid-template-columns:1fr}.fault-main{width:100%}h1{font-size:20px}}
</style></head>
<body>
<header><div class="top"><h1>⚡ <span id="appTitle"></span></h1><div class="top-actions"><div class="lang"><button onclick="setLang('ru')">RU</button><button onclick="setLang('he')">עברית</button><button onclick="setLang('en')">EN</button></div><button class="owner-btn" id="ownerBtn" onclick="ownerAccess()">🔒 Владелец</button></div></div></header>
<main class="workspace"><nav class="side"><button class="diamond-button" id="stockBtn" onclick="showPage('stock')"><div class="diamond"><div class="diamond-inner"><span class="icon">📦</span><span id="stockNav"></span></div></div></button><button class="diamond-button" id="machinesBtn" onclick="showPage('machines')"><div class="diamond"><div class="diamond-inner"><span class="icon">🏭</span><span id="machinesNav"></span></div></div></button></nav><section class="content">
<div id="stock" class="page active"><h2 id="stockTitle"></h2><div class="box" id="stockBox"></div></div>
<div id="machines" class="page"><h2 id="machinesTitle"></h2><p class="subtitle" id="machinesSub"></p><div class="machine-grid" id="machineGrid"></div></div>
<div id="thermoPage" class="page"><button class="back" onclick="showPage('machines')" id="thermoBack"></button><h2 id="thermoTitle"></h2><p class="subtitle" id="thermoSub"></p><button class="fault-main" id="thermoFaults" onclick="openThermoFaults()"></button><div class="section-grid" id="thermoGrid"></div></div>
<div id="thermoSectionPage" class="page"><button class="back" onclick="openThermo(currentMachineIndex)" id="thermoSectionBack"></button><h2 id="thermoSectionTitle"></h2><div class="section-info"><b id="thermoPartsTitle"></b><p id="thermoPartsText"></p></div></div>
<div id="machineDetail" class="page"><button class="back" onclick="showPage('machines')" id="backBtn"></button><h2 id="machineDetailTitle"></h2><div class="detail-grid"><button class="detail-tile" id="faultsTile" onclick="openGenericFaults()"></button><button class="detail-tile" id="partsTile"></button></div></div>
<div id="extruderPage" class="page"><button class="back" onclick="showPage('machines')" id="extruderBack"></button><h2 id="extruderTitle"></h2><p class="subtitle" id="extruderSub"></p><div class="section-grid" id="extruderGrid"></div></div>
<div id="extruderSectionPage" class="page"><button class="back" onclick="openExtruder(currentMachineIndex)" id="sectionBack"></button><h2 id="sectionTitle"></h2><div class="detail-grid"><button class="detail-tile" id="sectionFaults" onclick="openExtruderFaults()"></button><button class="detail-tile" id="sectionParts"></button></div></div>
<div id="faultPage" class="page"><button class="back" onclick="backFromFaults()" id="faultBack"></button><h2 id="faultTitle"></h2><div class="stats" id="stats"></div><div class="fault-form"><label id="dateLabel"></label><input type="date" id="faultDate"><label id="areaLabel"></label><select id="faultAreaSelect"></select><input id="faultAreaInput" style="display:none"><label id="faultLabel"></label><textarea id="faultText"></textarea><label id="repairLabel"></label><textarea id="repairText"></textarea><label id="replaceLabel"></label><input id="replaceText"><label id="photoLabel"></label><div class="file-row"><input class="native-file" type="file" accept="image/jpeg,image/png,image/webp" id="faultPhoto" onchange="updateFileNames()"><label class="file-btn" for="faultPhoto" id="photoChooseBtn"></label><span class="file-name" id="photoFileName"></span></div><div class="file-formats" id="photoFormats"></div><label id="documentLabel"></label><div class="file-row"><input class="native-file" type="file" accept="application/pdf,text/plain,.pdf,.txt" id="faultDocument" onchange="updateFileNames()"><label class="file-btn" for="faultDocument" id="documentChooseBtn"></label><span class="file-name" id="documentFileName"></span></div><div class="file-formats" id="documentFormats"></div><button class="save" onclick="saveFault()" id="saveBtn"></button></div><div class="records" id="records"></div></div>
</section></main>
<div class="modal" id="editModal"><div class="modal-card"><h3 id="editTitle">Изменение названия</h3><label>Русский</label><input id="editRu" oninput="scheduleTranslate()"><label>עברית</label><input id="editHe"><label>English</label><input id="editEn"><div class="hint" id="translateHint">Иврит и английский заполняются автоматически. При необходимости их можно исправить вручную.</div><div class="modal-actions"><button class="modal-btn" onclick="closeEdit()">Отмена</button><button class="modal-btn primary" onclick="saveEdit()">Сохранить</button></div></div></div>
<script>
let lang=localStorage.getItem('elektrikaLang')||'ru',currentMachineIndex=null,currentExtruderSection=null,currentThermoSection=null,faultMode='generic',ownerUnlocked=false,editTarget=null,translateTimer=null;
const defaults={machines:{ru:['Кефель 5','Кефель 6','Кефель 7','Кефель 8','Кефель 9','Кефель 10','Кефель 11','Кефель 12','Кефель 13','C1','C2','C3','RDM','Машина печати','Машина формовки стаканов','Экструдер 4','Экструдер 5','Экструдер 6'],he:['כפל 5','כפל 6','כפל 7','כפל 8','כפל 9','כפל 10','כפל 11','כפל 12','כפל 13','C1','C2','C3','RDM','מכונת דפוס','מכונת כוסות','אקסטרודר 4','אקסטרודר 5','אקסטרודר 6'],en:['Kefel 5','Kefel 6','Kefel 7','Kefel 8','Kefel 9','Kefel 10','Kefel 11','Kefel 12','Kefel 13','C1','C2','C3','RDM','Printing Machine','Cup Forming Machine','Extruder 4','Extruder 5','Extruder 6']},thermo:{ru:['Размотка','Цепной транспорт / подача пластика','Нагрев','Формовка','Нож / резка','Робот и выгрузка','Электрошкаф A','Электрошкаф B'],he:['פריסה','שרשרת והזנת פלסטיק','חימום','תרמופורמינג','סכין / חיתוך','רובוט ופריקה','לוח חשמל A','לוח חשמל B'],en:['Unwinding','Chain transport / plastic feed','Heating','Thermoforming','Knife / cutting','Robot and unloading','Electrical Cabinet A','Electrical Cabinet B']},extruder:{ru:['Станция дозирования','Экструдер A — главный','Экструдер B — вспомогательный','Каландр','Станция силикона','Ресивер','Узел намотки'],he:['תחנת מינון','אקסטרודר A — ראשי','אקסטרודר B — משני','קלנדר','תחנת סיליקון','רסיבר','גלילן'],en:['Dosing Station','Extruder A — Main','Extruder B — Secondary','Calender','Silicone Station','Receiver','Winding Unit']}};
function loadNames(type){let x=localStorage.getItem('names_'+type);return x?JSON.parse(x):JSON.parse(JSON.stringify(defaults[type]))}function saveNames(type,v){localStorage.setItem('names_'+type,JSON.stringify(v))}let machines=loadNames('machines'),thermoSections=loadNames('thermo'),extruderSections=loadNames('extruder');
const T={ru:{title:'Электрический склад',stock:'Общий склад',machines:'Машины',choose:'Выберите машину',back:'← Назад к машинам',faults:'Поломки',parts:'Электрические части',faultBack:'← Назад',date:'Дата поломки',area:'Часть машины',fault:'Какая поломка',repair:'Что сделал / ремонт',replace:'Замена электрической детали',photo:'Фотография поломки',choosePhoto:'Выбрать фотографию',photoFormats:'Форматы: JPG, JPEG, PNG, WEBP',document:'Документ',chooseDocument:'Прикрепить документ',documentFormats:'Форматы: PDF, TXT',noFile:'Файл не выбран',openDocument:'Открыть документ',save:'сохранить',stats:'Всего сохранённых поломок',extruderSub:'Выберите часть экструзионной линии',thermoSub:'Выберите станцию машины',partsTitle:'Электрические части этой станции',partsText:'Здесь будем хранить моторы, датчики, нагреватели, приводы, модели и другие электрические компоненты этой станции.',stockText:'Здесь будем отдельно строить общий склад.',owner:'🔒 Владелец',ownerOn:'🔓 Изменение'},he:{title:'מחסן חשמל',stock:'מחסן כללי',machines:'מכונות',choose:'בחר מכונה',back:'← חזרה למכונות',faults:'תקלות',parts:'חלקי חשמל',faultBack:'← חזרה',date:'תאריך התקלה',area:'חלק במכונה',fault:'מה התקלקל',repair:'מה עשיתי / תיקון',replace:'החלפת חלק חשמלי',photo:'תמונה של התקלה',choosePhoto:'בחר תמונה',photoFormats:'פורמטים: JPG, JPEG, PNG, WEBP',document:'מסמך',chooseDocument:'צרף מסמך',documentFormats:'פורמטים: PDF, TXT',noFile:'לא נבחר קובץ',openDocument:'פתח מסמך',save:'שמור',stats:'סה״כ תקלות שמורות',extruderSub:'בחר חלק מקו האקסטרוזיה',thermoSub:'בחר תחנה במכונה',partsTitle:'חלקי החשמל של התחנה',partsText:'כאן נשמור מנועים, חיישנים, גופי חימום, דרייבים, דגמים ורכיבים חשמליים של התחנה.',stockText:'כאן נבנה את המחסן הכללי.',owner:'🔒 בעלים',ownerOn:'🔓 עריכה'},en:{title:'Electrical Warehouse',stock:'General Warehouse',machines:'Machines',choose:'Select a machine',back:'← Back to machines',faults:'Faults',parts:'Electrical Parts',faultBack:'← Back',date:'Fault date',area:'Machine section',fault:'Fault description',repair:'What was done / repair',replace:'Electrical part replaced',photo:'Fault photo',choosePhoto:'Choose photo',photoFormats:'Formats: JPG, JPEG, PNG, WEBP',document:'Document',chooseDocument:'Attach document',documentFormats:'Formats: PDF, TXT',noFile:'No file selected',openDocument:'Open document',save:'save',stats:'Saved faults',extruderSub:'Select a section of the extrusion line',thermoSub:'Select a machine station',partsTitle:'Electrical parts for this station',partsText:'Here we will store motors, sensors, heaters, drives, models and other electrical components for this station.',stockText:'We will build the general warehouse here.',owner:'🔒 Owner',ownerOn:'🔓 Edit'}};
function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(p).classList.add('active')}
function tileHtml(name,type,i,click){return `<div class="tile-wrap"><button class="${type==='machines'?'machine':'section-tile'}" onclick="${click}">${esc(name)}</button><button class="edit-btn" onclick="event.stopPropagation();openEdit('${type}',${i})">✎</button></div>`}
function makeMachines(){machineGrid.innerHTML=machines[lang].map((n,i)=>tileHtml(n,'machines',i,`openMachine(${i})`)).join('')}
function openMachine(i){currentMachineIndex=i;currentExtruderSection=null;currentThermoSection=null;if(i<=11){openThermo(i);return}if(i>=15){openExtruder(i);return}machineDetailTitle.textContent=machines[lang][i];showPage('machineDetail')}
function openThermo(i){currentMachineIndex=i;thermoTitle.textContent=machines[lang][i];thermoSub.textContent=T[lang].thermoSub;thermoGrid.innerHTML=thermoSections[lang].map((n,idx)=>tileHtml(n,'thermo',idx,`openThermoSection(${idx})`)).join('');showPage('thermoPage')}
function openThermoSection(i){currentThermoSection=i;thermoSectionTitle.textContent=machines[lang][currentMachineIndex]+' — '+thermoSections[lang][i];thermoPartsTitle.textContent=T[lang].partsTitle;thermoPartsText.textContent=T[lang].partsText;showPage('thermoSectionPage')}
function openExtruder(i){currentMachineIndex=i;extruderTitle.textContent=machines[lang][i];extruderSub.textContent=T[lang].extruderSub;extruderGrid.innerHTML=extruderSections[lang].map((n,idx)=>tileHtml(n,'extruder',idx,`openExtruderSection(${idx})`)).join('');showPage('extruderPage')}
function openExtruderSection(i){currentExtruderSection=i;sectionTitle.textContent=machines[lang][currentMachineIndex]+' — '+extruderSections[lang][i];showPage('extruderSectionPage')}
function todayLocal(){let d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${d.getFullYear()}-${m}-${day}`}
function openThermoFaults(){faultMode='thermo';openFaultsCommon()}function openGenericFaults(){faultMode='generic';openFaultsCommon()}function openExtruderFaults(){faultMode='extruder';openFaultsCommon()}
function openFaultsCommon(){faultDate.value=todayLocal();faultAreaSelect.innerHTML='';faultAreaInput.style.display='none';faultAreaSelect.style.display='block';if(faultMode==='thermo')thermoSections[lang].forEach((n,i)=>faultAreaSelect.add(new Option(n,i)));else if(faultMode==='extruder'){faultAreaSelect.add(new Option(extruderSections[lang][currentExtruderSection],currentExtruderSection))}else{faultAreaSelect.style.display='none';faultAreaInput.style.display='block'}let ttl=machines[lang][currentMachineIndex];if(faultMode==='extruder')ttl+=' — '+extruderSections[lang][currentExtruderSection];faultTitle.textContent=ttl+' — '+T[lang].faults;renderRecords();showPage('faultPage')}
function backFromFaults(){if(faultMode==='thermo')openThermo(currentMachineIndex);else if(faultMode==='extruder')openExtruderSection(currentExtruderSection);else showPage('machineDetail')}
function faultKey(){return faultMode==='extruder'?`faults_machine_${currentMachineIndex}_section_${currentExtruderSection}`:`faults_machine_${currentMachineIndex}`}
function currentArea(){if(faultMode==='thermo')return thermoSections.ru[Number(faultAreaSelect.value)];if(faultMode==='extruder')return extruderSections.ru[currentExtruderSection];return faultAreaInput.value}
function fileData(file){return new Promise(resolve=>{if(!file){resolve({data:'',name:''});return}let r=new FileReader();r.onload=e=>resolve({data:e.target.result,name:file.name});r.onerror=()=>resolve({data:'',name:''});r.readAsDataURL(file)})}
function updateFileNames(){photoFileName.textContent=faultPhoto.files[0]?faultPhoto.files[0].name:T[lang].noFile;documentFileName.textContent=faultDocument.files[0]?faultDocument.files[0].name:T[lang].noFile}
async function saveFault(){let photo=await fileData(faultPhoto.files[0]),doc=await fileData(faultDocument.files[0]);let a=JSON.parse(localStorage.getItem(faultKey())||'[]');a.unshift({date:faultDate.value,area:currentArea(),fault:faultText.value,repair:repairText.value,replace:replaceText.value,photo:photo.data||'',document:doc.data||'',documentName:doc.name||''});try{localStorage.setItem(faultKey(),JSON.stringify(a))}catch(e){alert(lang==='he'?'הקובץ גדול מדי.':lang==='en'?'The file is too large.':'Файл слишком большой.');return}faultText.value='';repairText.value='';replaceText.value='';faultPhoto.value='';faultDocument.value='';updateFileNames();renderRecords()}
function renderRecords(){let a=JSON.parse(localStorage.getItem(faultKey())||'[]');stats.textContent=T[lang].stats+': '+a.length;records.innerHTML='';a.forEach(x=>{let d=document.createElement('div');d.className='record';d.innerHTML=`<div class="record-date">${esc(x.date)}</div><div><b>${T[lang].area}:</b> ${esc(x.area)}</div><div><b>${T[lang].fault}:</b> ${esc(x.fault)}</div><div><b>${T[lang].repair}:</b> ${esc(x.repair)}</div><div><b>${T[lang].replace}:</b> ${esc(x.replace)}</div>${x.photo?`<img src="${x.photo}">`:''}${x.document?`<div><a class="record-doc" href="${x.document}" download="${esc(x.documentName||'document')}">${T[lang].openDocument}: ${esc(x.documentName||'')}</a></div>`:''}`;records.appendChild(d)})}
function esc(s){let d=document.createElement('div');d.textContent=s||'';return d.innerHTML}
async function hashText(s){let b=new TextEncoder().encode(s),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function ownerAccess(){let saved=localStorage.getItem('owner_code_hash');if(!saved){let c=prompt('Создайте личный код доступа:');if(!c)return;let c2=prompt('Повторите код:');if(c!==c2){alert('Коды не совпадают');return}localStorage.setItem('owner_code_hash',await hashText(c));alert('Код доступа создан. Запомните его.')}else if(!ownerUnlocked){let c=prompt('Введите код доступа:');if(!c)return;if(await hashText(c)!==saved){alert('Неверный код');return}}ownerUnlocked=!ownerUnlocked;document.body.classList.toggle('owner-mode',ownerUnlocked);ownerBtn.classList.toggle('unlocked',ownerUnlocked);ownerBtn.textContent=ownerUnlocked?T[lang].ownerOn:T[lang].owner}
function openEdit(type,i){if(!ownerUnlocked)return;editTarget={type,i};let data=type==='machines'?machines:type==='thermo'?thermoSections:extruderSections;editRu.value=data.ru[i];editHe.value=data.he[i];editEn.value=data.en[i];editModal.classList.add('open')}
function closeEdit(){editModal.classList.remove('open');editTarget=null}
function scheduleTranslate(){clearTimeout(translateTimer);translateTimer=setTimeout(autoTranslate,500)}
async function autoTranslate(){let q=editRu.value.trim();if(!q)return;let known=smartTranslate(q);if(known){editHe.value=known.he;editEn.value=known.en;return}try{let [he,en]=await Promise.all([translateOnline(q,'he'),translateOnline(q,'en')]);if(he)editHe.value=he;if(en)editEn.value=en}catch(e){}}
function smartTranslate(q){let m=q.match(/^Кефель\s*(\d+)$/i);if(m)return{he:'כפל '+m[1],en:'Kefel '+m[1]};m=q.match(/^Экструдер\s*(\d+)$/i);if(m)return{he:'אקסטרודר '+m[1],en:'Extruder '+m[1]};let d={'Машина печати':['מכונת דפוס','Printing Machine'],'Машина формовки стаканов':['מכונת כוסות','Cup Forming Machine'],'Электрошкаф A':['לוח חשמל A','Electrical Cabinet A'],'Электрошкаф B':['לוח חשמל B','Electrical Cabinet B']};return d[q]?{he:d[q][0],en:d[q][1]}:null}
async function translateOnline(q,target){let u='https://translate.googleapis.com/translate_a/single?client=gtx&sl=ru&tl='+target+'&dt=t&q='+encodeURIComponent(q),r=await fetch(u);if(!r.ok)return'';let j=await r.json();return j[0].map(x=>x[0]).join('')}
function saveEdit(){if(!editTarget)return;let data=editTarget.type==='machines'?machines:editTarget.type==='thermo'?thermoSections:extruderSections;data.ru[editTarget.i]=editRu.value.trim();data.he[editTarget.i]=editHe.value.trim();data.en[editTarget.i]=editEn.value.trim();saveNames(editTarget.type,data);closeEdit();refreshCurrent()}
function refreshCurrent(){makeMachines();if(document.getElementById('thermoPage').classList.contains('active'))openThermo(currentMachineIndex);if(document.getElementById('extruderPage').classList.contains('active'))openExtruder(currentMachineIndex);if(currentThermoSection!==null&&document.getElementById('thermoSectionPage').classList.contains('active'))openThermoSection(currentThermoSection);if(currentExtruderSection!==null&&document.getElementById('extruderSectionPage').classList.contains('active'))openExtruderSection(currentExtruderSection)}
function setLang(l){lang=l;localStorage.setItem('elektrikaLang',l);let t=T[l];document.documentElement.lang=l;document.documentElement.dir=l==='he'?'rtl':'ltr';appTitle.textContent=t.title;stockNav.textContent=t.stock;machinesNav.textContent=t.machines;stockTitle.textContent=t.stock;stockBox.textContent=t.stockText;machinesTitle.textContent=t.machines;machinesSub.textContent=t.choose;thermoBack.textContent=t.back;thermoSub.textContent=t.thermoSub;thermoFaults.textContent=t.faults;thermoSectionBack.textContent=t.back;backBtn.textContent=t.back;faultsTile.textContent=t.faults;partsTile.textContent=t.parts;extruderBack.textContent=t.back;extruderSub.textContent=t.extruderSub;sectionBack.textContent=t.back;sectionFaults.textContent=t.faults;sectionParts.textContent=t.parts;faultBack.textContent=t.faultBack;dateLabel.textContent=t.date;areaLabel.textContent=t.area;faultLabel.textContent=t.fault;repairLabel.textContent=t.repair;replaceLabel.textContent=t.replace;photoLabel.textContent=t.photo;photoChooseBtn.textContent=t.choosePhoto;photoFormats.textContent=t.photoFormats;documentLabel.textContent=t.document;documentChooseBtn.textContent=t.chooseDocument;documentFormats.textContent=t.documentFormats;saveBtn.textContent=t.save;ownerBtn.textContent=ownerUnlocked?t.ownerOn:t.owner;updateFileNames();makeMachines();refreshCurrent();if(document.getElementById('faultPage').classList.contains('active'))openFaultsCommon()}
setLang(lang);
</script></body></html>'''

@app.route('/')
def home(): return render_template_string(HTML)

if __name__ == '__main__': app.run(debug=True)
