def apply(legacy):
    patch=r'''<script>
(function(){
function tx(ru,he,en){return lang==='he'?he:lang==='en'?en:ru}
function esc2(s){return esc(String(s??''))}
// Main warehouse: persistent drawing/schematic designation.
inventory.forEach(x=>{if(typeof x.drawingNo==='undefined')x.drawingNo=''});try{localStorage.setItem('warehouse_inventory_v2',JSON.stringify(inventory))}catch(e){}
const modal=document.querySelector('#warehouseEditModal .modal-card');
if(modal&&!document.getElementById('wiDrawingNo')){let before=document.getElementById('wlModel'),lab=document.createElement('label'),inp=document.createElement('input');lab.id='wlDrawingNo';inp.id='wiDrawingNo';inp.autocomplete='off';modal.insertBefore(lab,before);modal.insertBefore(inp,before)}
function whTexts(){let l=document.getElementById('wlDrawingNo');if(l)l.textContent=tx('Номер на чертеже','מספר בשרטוט','Drawing number')}
const oldOpen=window.openWarehouseEdit;window.openWarehouseEdit=function(i){oldOpen(i);let x=i>=0?inventory[i]:null;document.getElementById('wiDrawingNo').value=x&&x.drawingNo||'';whTexts()}
const oldSave=window.saveWarehouseItem;window.saveWarehouseItem=function(){let val=(document.getElementById('wiDrawingNo')||{}).value||'';let before=currentWarehouseEditIndex;oldSave();if(before>=0&&inventory[before])inventory[before].drawingNo=val.trim();else if(before<0&&inventory.length)inventory[inventory.length-1].drawingNo=val.trim();try{localStorage.setItem('warehouse_inventory_v2',JSON.stringify(inventory))}catch(e){}if(currentWarehouseCat)renderWarehouseItems()}
const oldRender=window.renderWarehouseItems;window.renderWarehouseItems=function(){oldRender();let table=document.querySelector('#warehouseCategory table'),hr=table&&table.querySelector('thead tr');if(!hr)return;if(!hr.querySelector('.drawing-th')){let th=document.createElement('th');th.className='drawing-th';let code=hr.querySelector('#thInternalCode')||hr.firstElementChild;code.insertAdjacentElement('afterend',th)}hr.querySelector('.drawing-th').textContent=tx('Номер на чертеже','מספר בשרטוט','Drawing number');document.querySelectorAll('#warehouseItemsBody tr[data-widx]').forEach(r=>{if(r.querySelector('.drawing-td'))return;let i=Number(r.dataset.widx),td=document.createElement('td');td.className='drawing-td';td.textContent=inventory[i]&&inventory[i].drawingNo||'';r.firstElementChild.insertAdjacentElement('afterend',td)})}
// Machine tables: add the same field to every machine/section table and edit modal.
const mp=document.querySelector('#machinePartModal .machine-parts-modal');if(mp&&!document.getElementById('mpDrawingNo')){let before=document.getElementById('mpLModel'),lab=document.createElement('label'),inp=document.createElement('input');lab.id='mpLDrawingNo';inp.id='mpDrawingNo';mp.insertBefore(lab,before);mp.insertBefore(inp,before)}
function mpTexts(){let l=document.getElementById('mpLDrawingNo');if(l)l.textContent=tx('Номер на чертеже','מספר בשרטוט','Drawing number')}
const oldMpOpen=window.openMachinePartEdit;window.openMachinePartEdit=function(i){oldMpOpen(i);let a=[];try{let d=JSON.parse(localStorage.getItem('machine_parts_v1')||'{}'),k=ctx.type+':'+ctx.machine+(ctx.section===null?'':':'+ctx.section);a=d[k]||[]}catch(e){}document.getElementById('mpDrawingNo').value=i>=0&&a[i]?a[i].drawingNo||'':'';mpTexts()}
const oldMpSave=window.saveMachinePart;window.saveMachinePart=function(){let v=(document.getElementById('mpDrawingNo')||{}).value||'',i=editIndex;oldMpSave();try{let d=JSON.parse(localStorage.getItem('machine_parts_v1')||'{}'),k=ctx.type+':'+ctx.machine+(ctx.section===null?'':':'+ctx.section),a=d[k]||[],j=i>=0?i:a.length-1;if(j>=0&&a[j]){a[j].drawingNo=v.trim();d[k]=a;localStorage.setItem('machine_parts_v1',JSON.stringify(d))}}catch(e){}setTimeout(addMachineColumns,0)}
function addMachineColumns(){document.querySelectorAll('.machine-parts-wrap table').forEach(t=>{let hr=t.querySelector('thead tr');if(!hr)return;if(!hr.querySelector('.mp-drawing-th')){let th=document.createElement('th');th.className='mp-drawing-th';hr.children[0].insertAdjacentElement('afterend',th)}hr.querySelector('.mp-drawing-th').textContent=tx('Номер на чертеже','מספר בשרטוט','Drawing number');let rows=t.querySelectorAll('tbody tr');let data=[];try{let d=JSON.parse(localStorage.getItem('machine_parts_v1')||'{}');if(ctx){let k=ctx.type+':'+ctx.machine+(ctx.section===null?'':':'+ctx.section);data=d[k]||[]}}catch(e){}rows.forEach((r,i)=>{if(r.querySelector('.mp-drawing-td')||r.querySelector('.machine-parts-empty'))return;let td=document.createElement('td');td.className='mp-drawing-td';td.textContent=data[i]&&data[i].drawingNo||'';r.children[0].insertAdjacentElement('afterend',td)})})}
document.addEventListener('click',()=>setTimeout(addMachineColumns,0));document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{whTexts();mpTexts();if(currentWarehouseCat)renderWarehouseItems();addMachineColumns()},0)));whTexts();mpTexts();setTimeout(addMachineColumns,0);
})();
</script>'''
    legacy.HTML=legacy.HTML.replace('</body>',patch+'</body>')
