def apply(legacy):
    patch = r'''<style>
#e4DrawingGroups{display:none!important}.e4loc{margin:14px 0 18px}.e4loc-title{font-size:18px;font-weight:800;margin:0 0 10px}.e4loc-note{font-size:13px;color:#607277;margin-bottom:12px}.e4loc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px}.e4loc-card{border:1px solid #cbd8d9;border-radius:12px;background:#fff;padding:14px}.e4loc-card h3{margin:0 0 6px;font-size:16px}.e4loc-zone{display:inline-block;margin-bottom:10px;padding:3px 8px;border-radius:999px;background:#edf3f2;font-size:12px;font-weight:800}.e4loc-table{width:100%;border-collapse:collapse}.e4loc-table th,.e4loc-table td{padding:7px 6px;border-bottom:1px solid #e5ebeb;text-align:left;vertical-align:top;font-size:13px}.e4loc-table th{font-size:12px;color:#5b6d71}.e4loc-empty{padding:10px;border:1px dashed #c6d2d3;border-radius:9px;color:#64767a;font-size:13px;line-height:1.45}.e4main-drives{margin:12px 0 18px;padding:14px;border:1px solid #cbd8d9;border-radius:12px;background:#fff}.e4main-drives h3{margin:0 0 5px}.e4main-drives .sub{font-size:13px;color:#617378;margin-bottom:10px}.e4main-wrap{overflow:auto;max-height:520px}.e4main-drives table{width:100%;border-collapse:collapse;min-width:920px}.e4main-drives th,.e4main-drives td{padding:8px;border-bottom:1px solid #e3eaea;text-align:left;vertical-align:top}.e4main-drives th{position:sticky;top:0;background:#f7faf9;font-size:12px;color:#56686c}
</style><script>
(function(){
 function tx(ru,he,en){return lang==='he'?he:lang==='en'?en:ru}
 function esc2(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function machineName(){return ((machines[lang]||[])[currentMachineIndex]||'')}
 function isE4(){let n=machineName().toLowerCase();return n.includes('4')&&(n.includes('экструдер')||n.includes('אקסטרודר')||n.includes('extruder'))}
 function sectionName(){return ((extruderSections[lang]||[])[currentExtruderSection]||'')}
 function skey(){let s=sectionName().toLowerCase();if(s.includes('кал')||s.includes('קלנ')||s.includes('cal'))return'calender';if((s.includes('a')||s.includes('משני'))&&(s.includes('extr')||s.includes('אקס')))return'a';if((s.includes('b')||s.includes('ראשי'))&&(s.includes('extr')||s.includes('אקס')))return'b';if(s.includes('доз')||s.includes('מינון')||s.includes('dos'))return'dosing';if(s.includes('силик')||s.includes('סיליק')||s.includes('silic'))return'silicone';if(s.includes('рес')||s.includes('רסיב')||s.includes('receiv'))return'receiver';if(s.includes('wind')||s.includes('גליל')||s.includes('намот'))return'winding';return'other'}
 const mainDrives=[
  ['-38U1','ABB ACS 800-01-0006-3','Extruder A volumetric pump','3.9 kW; ADD=26'],
  ['-43U1','ABB ACS 800-01-0030-3','Extruder B volumetric pump','20.3 kW; 390 V; 42.5 A; ADD=16'],
  ['-53U1','ABB ACS 800-01-0100-3','Extruder A','75 kW; 400 V; 136 A; ADD=21'],
  ['-61U1','ABB ACS 800-04-0400-3','Extruder B','315 kW; 400 V; 529 A; ADD=11'],
  ['-91U1','ABB ACS 800-01-0011-3','Calender inlet roll','6.5 kW; 380 V; 14.8 A; ADD=70'],
  ['-95U1','ABB ACS 800-01-0020-3','Calender central roll','12 kW; 380 V; 27.5 A; ADD=71'],
  ['-99U1','ABB ACS 800-01-0011-3','Calender outlet roll','6.5 kW; 380 V; 14.8 A; ADD=72'],
  ['-110U1','ABB ACS 550-01-03A3-4J-404','Calender movement','0.25 kW'],
  ['-120U1','ABB ACS 800-01-0006-3','Cooling roll','4.0 kW; 380 V; 10.0 A; ADD=73'],
  ['-130U1','ABB ACS 800-01-0005-3','Take-off','2.7 kW; 380 V; 7 A; ADD=81'],
  ['-145U1','ABB ACS 550-01-03A3-4J-404','Pressure roll','0.25 kW; 400 V; 0.78 A; ADD=75'],
  ['-152U1','ABB ACS 550-01-04A1-4','Uncoiler 1','ADD=76'],
  ['-162U1','ABB ACS 550-01-04A1-4','Uncoiler 2','ADD=77']
 ];
 const field={
  calender:[['-91M1','Inlet roll motor','AX 100K.2','6.5 kW'],['-95M1','Central roll motor','AX 100K.4','12 kW'],['-99M1','Outlet roll motor','AX 100K.2','6.5 kW'],['-120M1','Cooling roll motor','AX 80CS.2','4.0 kW'],['-130M1','Take-off motor','AX 80CS.075','2.7 kW'],['-94M1','Inlet roll motor fan','','0.075 kW'],['-123M1','Cooling roll motor fan','','0.025 kW'],['-147M1','Pressure roll motor fan','','0.025 kW']],
  a:[['-53M1','Extruder A motor','ABB M3AA 250 SMB','75 kW'],['-38M1','Extruder A volumetric pump motor','LENZE MCA 14L35','3.9 kW'],['-39M1','Extruder A pump motor fan','',''],['-41M1','Extruder A pump motor fan','','0.019 kW']],
  b:[['-61M1','Extruder B motor','ABB M2BA 355 SMA4','315 kW'],['-43M1','Extruder B volumetric pump motor','LENZE MCA 21X35','20.3 kW']]
 };
 const cabinetInfo={
  calender:{zone:'+17',name:['Локальный электрический шкаф каландера','ארון חשמל מקומי של הקלנדר','Calender local electrical cabinet'],src:'CALENDER BOX / CASSETTA CALANDRA',note:['В текущем комплекте S.3144 группы +2 подтверждён интерфейс центрального шкафа с +17 через X117. Полный внутренний список деталей шкафа +17 в этом комплекте не найден, поэтому я его не выдумываю.','בסט S.3144 של קבוצה +2 מאומת ממשק מהארון הראשי אל +17 דרך X117. רשימת החלקים הפנימית המלאה של ארון +17 לא נמצאה בסט הזה ולכן אינה מומצאת.','In the current S.3144 group +2 set, the interface from the main cabinet to +17 is confirmed through X117. A complete internal BOM for cabinet +17 was not found in this set, so it is not invented.']},
  a:{zone:'local boxes',name:['Локальные шкафы терморегулирования Extruder A','ארונות ויסות טמפרטורה מקומיים אקסטרודר A','Extruder A local temperature-control boxes'],src:'INSTALLATION ZONES',note:['В схеме отдельно указаны шкаф терморегулирования Extruder A и шкаф pump+pipes. Внутренний BOM этих локальных шкафов будем добавлять только по их собственным листам/материалам.','בשרטוט מצוינים בנפרד ארון ויסות טמפרטורה של Extruder A וארון pump+pipes. BOM פנימי יתווסף רק מהשרטוטים שלהם.','The drawing lists separate Extruder A temperature-control and pump+pipes boxes. Their internal BOM will be added only from their own sheets/material lists.']},
  b:{zone:'local boxes',name:['Локальные шкафы терморегулирования Extruder B','ארונות ויסות טמפרטורה מקומיים אקסטרודר B','Extruder B local temperature-control boxes'],src:'INSTALLATION ZONES',note:['Отдельно указаны temperature regulation box, screenchanger box и pump+pipes box. Внутренние элементы не смешиваются с главным шкафом +2.','מצוינים בנפרד temperature regulation box, screenchanger box ו-pump+pipes box. הרכיבים הפנימיים אינם מעורבבים עם הארון הראשי +2.','Separate temperature regulation, screenchanger, and pump+pipes boxes are listed. Their internal components are not mixed with main cabinet +2.']}
 };
 function tableRows(rows){if(!rows||!rows.length)return'<div class="e4loc-empty">'+tx('В этом разделе пока нет подтверждённых полевых позиций из загруженного комплекта.','אין עדיין פריטי שדה מאומתים מהסט הטעון בסעיף זה.','No field items are yet confirmed from the loaded set for this section.')+'</div>';return'<table class="e4loc-table"><thead><tr><th>'+tx('Номер на чертеже','מספר בשרטוט','Drawing designation')+'</th><th>'+tx('Оборудование','ציוד','Equipment')+'</th><th>'+tx('Модель','דגם','Model')+'</th><th>'+tx('Данные','נתונים','Data')+'</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><b>'+esc2(r[0])+'</b></td><td>'+esc2(r[1])+'</td><td>'+esc2(r[2]||'—')+'</td><td>'+esc2(r[3]||'—')+'</td></tr>').join('')+'</tbody></table>'}
 function renderSection(){if(!isE4())return;let host=document.getElementById('extruderSectionPage');if(!host||!host.classList.contains('active'))return;let old=document.getElementById('e4LocationSplit');if(old)old.remove();let k=skey(),ci=cabinetInfo[k]||{zone:'—',name:[tx('Локальный электрический шкаф','ארון חשמל מקומי','Local electrical cabinet')],src:'',note:[tx('Для этого участка точный локальный шкаф ещё не подтверждён по загруженным листам.','הארון המקומי המדויק של אזור זה עדיין לא אומת מהדפים שהועלו.','The exact local cabinet for this section has not yet been confirmed from the uploaded sheets.') ]};let n=ci.name.length===3?(lang==='he'?ci.name[1]:lang==='en'?ci.name[2]:ci.name[0]):ci.name[0];let note=ci.note.length===3?(lang==='he'?ci.note[1]:lang==='en'?ci.note[2]:ci.note[0]):ci.note[0];let d=document.createElement('div');d.id='e4LocationSplit';d.className='e4loc';d.innerHTML='<div class="e4loc-title">'+tx('Разделение по физическому месту установки','חלוקה לפי מקום התקנה פיזי','Split by physical installation location')+'</div><div class="e4loc-note">'+tx('Главный шкаф, локальный шкаф участка и полевое оборудование больше не смешиваются.','הארון הראשי, הארון המקומי וציוד השדה אינם מעורבבים יותר.','Main cabinet, local section cabinet, and field equipment are no longer mixed.')+'</div><div class="e4loc-grid"><div class="e4loc-card"><h3>'+esc2(n)+'</h3><div class="e4loc-zone">'+esc2(ci.zone)+' · '+esc2(ci.src)+'</div><div class="e4loc-empty">'+esc2(note)+'</div></div><div class="e4loc-card"><h3>'+tx('Полевое оборудование участка','ציוד שדה של האזור','Section field equipment')+'</h3><div class="e4loc-zone">'+tx('Вне шкафов','מחוץ לארונות','Outside cabinets')+'</div>'+tableRows(field[k]||[])+'</div></div>';let p=document.getElementById('extruderSectionPanelBlock')||document.getElementById('extruderPartsInline');host.insertBefore(d,p||host.firstChild)}
 function renderMain(){if(!isE4())return;let h=document.getElementById('extruderMainPanelBlock');if(!h)return;let old=document.getElementById('e4MainPhysicalDrives');if(old)old.remove();let d=document.createElement('div');d.id='e4MainPhysicalDrives';d.className='e4main-drives';d.innerHTML='<h3>'+tx('Главный электрический шкаф +2 — приводы, физически установленные в шкафу','ארון חשמל ראשי +2 — דרייבים שמותקנים פיזית בארון','Main electrical cabinet +2 — drives physically installed in the cabinet')+'</h3><div class="sub">'+tx('Функция привода может относиться к Calender / Extruder / Uncoiler, но место установки остаётся главный шкаф +2. Номер U хранится как «Номер на чертеже».','תפקיד הדרייב יכול להיות Calender / Extruder / Uncoiler, אבל מקום ההתקנה נשאר הארון הראשי +2. מספר U נשמר כ״מספר בשרטוט״.','A drive may serve Calender / Extruder / Uncoiler, but its installation location remains main cabinet +2. The U identifier is stored as the drawing designation.')+'</div><div class="e4main-wrap"><table><thead><tr><th>'+tx('Номер на чертеже','מספר בשרטוט','Drawing designation')+'</th><th>'+tx('Модель / Part No.','דגם / מק״ט','Model / Part No.')+'</th><th>'+tx('Назначение','ייעוד','Function')+'</th><th>'+tx('Данные','נתונים','Data')+'</th><th>'+tx('Физическое место','מיקום פיזי','Physical location')+'</th></tr></thead><tbody>'+mainDrives.map(r=>'<tr><td><b>'+esc2(r[0])+'</b></td><td>'+esc2(r[1])+'</td><td>'+esc2(r[2])+'</td><td>'+esc2(r[3])+'</td><td><b>+2</b></td></tr>').join('')+'</tbody></table></div>';h.parentNode.insertBefore(d,h)}
 const os=window.openExtruderSection;window.openExtruderSection=function(i){os(i);setTimeout(renderSection,160)};
 const om=window.openExtruderMainPanel;if(om)window.openExtruderMainPanel=function(){om();setTimeout(renderMain,180)};
 document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{renderSection();renderMain()},180)));
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
