def apply(legacy):
    patch = r'''<style>
.ep-block{margin:16px 0;padding:14px;border:1px solid #ccd7d8;border-radius:12px;background:#fff}.ep-title{font-size:17px;font-weight:700;margin:0 0 8px}.ep-add{display:inline-block;margin:4px 0 10px;padding:10px 15px;border:0;border-radius:9px;background:#527d83;color:#fff;font-weight:700;cursor:pointer}.ep-wrap{overflow:auto;border:1px solid #ccd7d8;border-radius:10px;background:#fff}.ep-wrap table{min-width:860px}.ep-actions button{padding:4px 7px;cursor:pointer}.ep-empty{padding:18px;color:#718087}.ep-match{margin-top:8px;padding:9px 10px;border-radius:8px;background:#eef5f3;font-size:13px;line-height:1.4}.ep-match:empty{display:none}.ep-dup{background:#fff2e8}
</style>
<div class="page" id="extruderMainPanelPage"><button class="back" id="epMainBack"></button><h2 id="epMainPageTitle"></h2><div id="extruderMainPanelBlock" class="ep-block"></div></div>
<div class="modal" id="epModal"><div class="modal-card"><h3 id="epModalTitle"></h3><label id="epLCode"></label><input id="epCode"><label id="epLModel"></label><input id="epModel"><div id="epMatch" class="ep-match"></div><label id="epLMfr"></label><input id="epMfr"><label id="epLSpecs"></label><textarea id="epSpecs"></textarea><label id="epLQty"></label><input id="epQty" type="number" min="0" step="1"><label id="epLPrice"></label><input id="epPrice" type="number" step="0.01"><label id="epLNotes"></label><textarea id="epNotes"></textarea><div class="modal-actions"><button class="modal-btn" id="epCancel" onclick="closeExtruderPanelEdit()"></button><button class="modal-btn primary" id="epSave" onclick="saveExtruderPanelItem()"></button></div></div></div>
<script>
(function(){
 const KEY='machine_parts_v1';let epCtx=null,epEdit=-1;
 function tx(ru,he,en){return lang==='he'?he:lang==='en'?en:ru}function e(s){return esc(String(s??''))}function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,'')}function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return{}}}function save(d){localStorage.setItem(KEY,JSON.stringify(d))}function machineName(i){return (machines[lang]&&machines[lang][i])||''}function sectionName(i){return (extruderSections[lang]&&extruderSections[lang][i])||''}function keyFor(c){return c.kind==='main'?'panel-main:'+c.machine:'panel-section:'+c.machine+':'+c.section}function items(c){let d=load();return d[keyFor(c||epCtx)]||[]}function store(a,c){let d=load();d[keyFor(c||epCtx)]=a;save(d)}function mainCtx(){return{kind:'main',machine:currentMachineIndex,section:null}}function sectionCtx(){return{kind:'section',machine:currentMachineIndex,section:currentExtruderSection}}
 function title(c){return c.kind==='main'?machineName(c.machine)+' — '+tx('Главный электрический ящик','לוח חשמל ראשי','Main electrical cabinet'):machineName(c.machine)+' — '+tx('Электрощит','לוח חשמל','Electrical cabinet')+' — '+sectionName(c.section)}
 function headers(){return `<thead><tr><th>${tx('Код','קוד','Code')}</th><th>${tx('Модель / артикул','דגם / מק״ט','Model / part no.')}</th><th>${tx('Фирма','יצרן','Manufacturer')}</th><th>${tx('Параметры','נתונים','Specifications')}</th><th>${tx('Количество','כמות','Quantity')}</th><th>${tx('Цена','מחיר','Price')}</th><th>${tx('Примечание','הערה','Notes')}</th><th>${tx('Изменение','עריכה','Edit')}</th></tr></thead>`}
 function table(c){let a=items(c);return `<div class="ep-wrap"><table>${headers()}<tbody>${a.length?a.map((x,i)=>`<tr><td><b>${e(x.code)}</b></td><td>${e(x.model)}</td><td>${e(x.mfr)}</td><td>${e(x.specs)}</td><td class="qty">${e(x.qty)}</td><td>${x.price!==''?e(x.price):''}</td><td>${e(x.notes)}</td><td class="ep-actions"><button onclick="openExtruderPanelEdit('${c.kind}',${c.machine},${c.section===null?'null':c.section},${i})">✎</button></td></tr>`).join(''):`<tr><td colspan="8" class="ep-empty">${tx('Пока ничего не добавлено','עדיין לא נוסף דבר','Nothing added yet')}</td></tr>`}</tbody></table></div>`}
 function block(c){return `<div class="ep-title">⚡ ${e(title(c))}</div><button class="ep-add" onclick="openExtruderPanelEdit('${c.kind}',${c.machine},${c.section===null?'null':c.section},-1)">${tx('+ Новая позиция','+ פריט חדש','+ New item')}</button>${table(c)}`}
 function renderMain(){let host=document.getElementById('extruderMainPanelBlock');if(!host||currentMachineIndex===null)return;host.innerHTML=block(mainCtx());epMainPageTitle.textContent=tx('Главный электрический ящик','לוח חשמל ראשי','Main electrical cabinet');epMainBack.textContent=tx('← Назад','← חזרה','← Back')}
 function renderSection(){let host=document.getElementById('extruderSectionPanelBlock');if(!host||currentMachineIndex===null||currentExtruderSection===null)return;host.innerHTML=block(sectionCtx())}
 window.openExtruderMainPanel=function(){renderMain();epMainBack.onclick=()=>openExtruder(currentMachineIndex);showPage('extruderMainPanelPage')}
 function addMainTile(){let g=document.getElementById('extruderGrid');if(!g||currentMachineIndex===null)return;let old=document.getElementById('extruderMainPanelTile');if(old)old.remove();let w=document.createElement('div');w.className='tile-wrap';w.id='extruderMainPanelTile';w.innerHTML=`<button class="section-tile" onclick="openExtruderMainPanel()">${tx('Главный электрический ящик','לוח חשמל ראשי','Main electrical cabinet')}</button>`;g.insertBefore(w,g.firstChild)}
 function syncModal(){if(!epCtx)return;epModalTitle.textContent=title(epCtx);epLCode.textContent=tx('Код склада / внутренний код','קוד מחסן / קוד פנימי','Warehouse / internal code');epLModel.textContent=tx('Модель / артикул','דגם / מק״ט','Model / part no.');epLMfr.textContent=tx('Фирма','יצרן','Manufacturer');epLSpecs.textContent=tx('Параметры','נתונים','Specifications');epLQty.textContent=tx('Количество в этом щите','כמות בלוח הזה','Quantity in this cabinet');epLPrice.textContent=tx('Цена','מחיר','Price');epLNotes.textContent=tx('Примечание','הערה','Notes');epCancel.textContent=tx('Отмена','ביטול','Cancel');epSave.textContent=tx('Сохранить','שמור','Save')}
 function findMatches(){if(!epCtx)return;let q=norm(epModel.value),code=norm(epCode.value);if(q.length<3&&code.length<2){epMatch.textContent='';epMatch.classList.remove('ep-dup');return}let msg=[];let wh=inventory.filter(x=>(q&&norm(x.name)===q)||(code&&norm(x.internalCode)===code));if(wh.length)msg.push(tx('На главном складе: ','במחסן הראשי: ','Main warehouse: ')+wh.map(x=>`${x.name} — ${x.qty??0}`).join('; '));let d=load(),other=[];Object.keys(d).forEach(k=>(d[k]||[]).forEach(x=>{if((q&&norm(x.model)===q)||(code&&norm(x.code)===code))other.push(x)}));if(other.length)msg.push(tx('На машинах и щитах: ','במכונות ובלוחות: ','On machines and cabinets: ')+other.map(x=>`${x.model} × ${x.qty}`).join('; '));let same=items().some((x,i)=>i!==epEdit&&((q&&norm(x.model)===q)||(code&&norm(x.code)===code)));epMatch.textContent=msg.join(' | ')+(same?(msg.length?' | ':'')+tx('Эта позиция уже есть в этом щите.','הפריט כבר קיים בלוח הזה.','This item already exists in this cabinet.'):'');epMatch.classList.toggle('ep-dup',same)}
 window.openExtruderPanelEdit=function(kind,machine,section,i){epCtx={kind,machine,section};epEdit=i;let a=items(),x=i>=0?a[i]:{code:'',model:'',mfr:'',specs:'',qty:1,price:'',notes:''};epCode.value=x.code||'';epModel.value=x.model||'';epMfr.value=x.mfr||'';epSpecs.value=x.specs||'';epQty.value=x.qty??1;epPrice.value=x.price??'';epNotes.value=x.notes||'';syncModal();findMatches();epModal.classList.add('open')};window.closeExtruderPanelEdit=function(){epModal.classList.remove('open')};window.saveExtruderPanelItem=function(){let model=epModel.value.trim(),code=epCode.value.trim();if(!model)return;let a=items(),nm=norm(model),nc=norm(code),dup=a.findIndex((x,i)=>i!==epEdit&&((nm&&norm(x.model)===nm)||(nc&&norm(x.code)===nc)));if(dup>=0){alert(tx('Эта позиция уже есть в этом щите. Дубликат не добавлен.','הפריט כבר קיים בלוח הזה. לא נוסף כפול.','This item already exists in this cabinet. Duplicate was not added.'));return}let x={code,model,mfr:epMfr.value.trim(),specs:epSpecs.value.trim(),qty:Math.max(0,Number(epQty.value)||0),price:epPrice.value===''?'':Number(epPrice.value),notes:epNotes.value.trim()};if(epEdit>=0)a[epEdit]=x;else a.push(x);store(a);closeExtruderPanelEdit();renderMain();renderSection()};epModel.addEventListener('input',findMatches);epCode.addEventListener('input',findMatches);epMfr.addEventListener('input',findMatches);
 let sp=document.getElementById('extruderSectionPage');if(sp&&!document.getElementById('extruderSectionPanelBlock')){let d=document.createElement('div');d.id='extruderSectionPanelBlock';d.className='ep-block';sp.appendChild(d)}
 const oldOpenExtruder=window.openExtruder;window.openExtruder=function(i){oldOpenExtruder(i);setTimeout(addMainTile,0)};const oldOpenExtruderSection=window.openExtruderSection;window.openExtruderSection=function(i){oldOpenExtruderSection(i);setTimeout(renderSection,0)};document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{if(document.getElementById('extruderPage').classList.contains('active'))addMainTile();renderSection();if(document.getElementById('extruderMainPanelPage').classList.contains('active'))renderMain();if(epModal.classList.contains('open'))syncModal()},0)));
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
