def apply(legacy):
    patch = r'''<style>
#e5StationCatalog{margin:14px 0 20px;padding:15px;border:1px solid #d3ddde;border-radius:14px;background:#fff}.e5st-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px}.e5st-tile{min-height:72px;border:1px solid #cbd8d9;border-radius:11px;background:#f8fbfa;color:#34454b;font-size:15px;font-weight:700;padding:12px;cursor:pointer}.e5st-detail{margin-top:14px;border:1px solid #cbd8d9;border-radius:12px;padding:14px}.e5st-wrap{overflow:auto;max-height:580px}.e5st-table{width:100%;border-collapse:collapse;min-width:900px}.e5st-table th,.e5st-table td{padding:8px;border-bottom:1px solid #e3eaea;text-align:left;font-size:12px;vertical-align:top}.e5st-table th{position:sticky;top:0;background:#f4f8f7}.e5st-head{display:flex;justify-content:space-between;align-items:center}.e5st-back{padding:7px 11px;border:1px solid #cbd8d9;border-radius:8px;background:#f4f8f7;cursor:pointer}.e5st-location{font-size:13px;color:#5f7276;margin:4px 0 12px}@media(max-width:850px){.e5st-grid{grid-template-columns:repeat(2,minmax(140px,1fr))}}
</style><script>
(function(){
 function tx(a,b,c){return lang==='he'?b:lang==='en'?c:a} function x(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
 function isE5(){let n=((machines[lang]||[])[currentMachineIndex]||'').toLowerCase();return n.includes('5')&&(n.includes('экструдер')||n.includes('אקסטרודר')||n.includes('extruder'))}
 function sname(){return ((extruderSections[lang]||[])[currentExtruderSection]||'')}
 function skey(){let s=sname().toLowerCase();if((s.includes('extruder a')||s.includes('экструдер a')||s.includes('אקסטרודר a')||s.includes('משני')))return'a';if((s.includes('extruder b')||s.includes('экструдер b')||s.includes('אקסטרודר b')||s.includes('ראשי')))return'b';if(s.includes('cal')||s.includes('кал')||s.includes('קלנ'))return'calender';if(s.includes('wind')||s.includes('намот')||s.includes('גליל'))return'winding';if(s.includes('sil')||s.includes('силик')||s.includes('סיליק'))return'silicone';return'other'}
 const baseCats=[['drives',['Драйверы','דרייבים','Drives']],['motors',['Моторы','מנועים','Motors']],['starters',['Пускатели / защита','מתנעים / הגנה','Starters / protection']],['contactors',['Контакторы','קונטקטורים','Contactors']],['relays',['Реле','ממסרים','Relays']],['io',['PLC / I/O','PLC / I/O','PLC / I/O']],['sensors',['Датчики','חיישנים','Sensors']],['valves',['Клапаны / пневматика','שסתומים / פנאומטיקה','Valves / pneumatics']],['heating',['Нагрев','חימום','Heating']],['other',['Прочее','אחר','Other']]];
 const calCats=[['cab_drives',['Шкаф: драйверы','ארון: דרייבים','Cabinet: drives']],['cab_starters',['Шкаф: пускатели / защита','ארון: מתנעים / הגנה','Cabinet: starters / protection']],['cab_contactors',['Шкаф: контакторы','ארון: קונטקטורים','Cabinet: contactors']],['cab_io',['Шкаф: PLC / I/O','ארון: PLC / I/O','Cabinet: PLC / I/O']],['cab_safety',['Шкаф: Safety I/O','ארון: Safety I/O','Cabinet: Safety I/O']],['cab_power',['Шкаф: питание','ארון: ספקי כוח','Cabinet: power']],['field_motors',['Участок: моторы','שטח: מנועים','Field: motors']],['field_sensors',['Участок: датчики','שטח: חיישנים','Field: sensors']],['field_valves',['Участок: клапаны / гидравлика','שטח: שסתומים / הידראוליקה','Field: valves / hydraulics']],['field_other',['Участок: прочее','שטח: אחר','Field: other']]];
 const D={
 a:{drives:[['Главный привод Extruder A','-41U2','ABB','ACS880-01-169A-3','90 kW · 400 V · IP21']],motors:[['Мотор Extruder A','-41M2','ABB','M3BP 280SMB','90 kW · 160 A · 400 V · 50 Hz · 1483 rpm']]},
 b:{drives:[['Главный привод Extruder B','-81U2','ABB','ACS880-04-585A-3','315 kW · 400 V · IP20'],['Привод насоса Extruder B','-101U2','ABB','ACS880-01-045A-3','22 kW · 400 V · IP21']]},
 calender:{
  cab_drives:[['Привод','-685U1','ABB','ACS355-03E-01A2-4','Calender cabinet CK1 · frame R0'],['Модуль Profinet привода','-685U7','ABB','FENA-11','Calender cabinet CK1'],['Приводы клиньев','-711U1 / -715U1 / -721U1 / -725U1','ABB','BSD0200','Calender cabinet CK1 · 0.2 kW axes'],['Привод перемещения','-751U1','ABB','ACS355-03E-01A9-4','Calender cabinet CK1 · frame R0'],['Модуль Profinet привода','-751U7','ABB','FENA-11','Calender cabinet CK1']],
  cab_starters:[['Реверсивный пускатель','-675Q1 / -678Q1','Siemens','3RM1302-2AA04','0.4–2.0 A · failsafe'],['Реверсивный пускатель','-755Q1','Siemens','3RM1307-2AA04','1.6–7.0 A · failsafe'],['Защита двигателя гидростанции','-761QM1','Siemens','3RV2011-1JA20 / 3RV2011-1HA20','7–10 A / 5.5–8 A']],
  cab_contactors:[['Контактор','-710KM4 / -710KM5','Siemens','3RT2025-2BB40','7.5 kW · 24 VDC · S0'],['Контактор','-761KM3','Siemens','3RT2016-2BB41','4 kW · 24 VDC · S00']],
  cab_io:[['ET200SP interface','-906A1','Siemens','6ES7155-6AU00-0CN0','IM155-6 PN HF'],['Аналоговый выход AQ','-932A0','Siemens','6ES7135-6HD00-0BA1','AQ 4xU/I ST ET200SP'],['Цифровой вход DI','-959A0','Siemens','6ES7131-6BF60-0AA0','DI 8x24VDC SCR BA'],['Цифровой выход DQ','-976A0','Siemens','6ES7132-6BF60-0AA0','DQ 8x24VDC/0.5A SINK BA']],
  cab_safety:[['Safety PLC / F-I/O','-942A0…-945A0','Siemens','','Safe PLC overview / failsafe I/O in CK1']],
  cab_power:[['Питание и вспомогательные цепи','CK1 pages 848+','', '', 'Auxiliary circuit / cabinet supply']],
  field_motors:[['Мотор левого входного клина','-711M1','ABB','BSM0200CN00','0.2 kW · 1.5 A · 91 V · 200 Hz · 3000 rpm'],['Мотор левого выходного клина','-721M1','ABB','BSM0200CN00','0.2 kW · 1.5 A · 91 V · 200 Hz · 3000 rpm'],['Мотор насоса гидростанции','-761M1','', '', 'Calender oleodynamic unit']],
  field_sensors:[['Тензодатчик тяги','791 / 1120','', '', 'Haul-off load cell'],['Пирометр температуры материала','793','', '', 'Material temperature pyrometer'],['Датчик давления валов','768','', '', 'Roll pressure measurement']],
  field_valves:[['Гидравлические электроклапаны','763–765','', '', 'Calender oleodynamic unit']],
  field_other:[['Jog каландера','785','', '', 'Calender jog circuit'],['Аварийная цепь участка','786','', '', 'Line emergency'],['Регулирование размотчика','832','', '', 'Unwinder regulation associated with calender']]
 },
 winding:{drives:[['Trim winder drive','-862U1 / -866U1','ABB','ACS550-01-04A1-4','1.5 kW']]},silicone:{sensors:[['Take-off load cell','792','', '', 'Siliconator take-off load cell']]},other:{other:[['Head box','CT1','', '', 'Head/feedblock thermoregulation and screenchanger interface']]}
 };
 let selected=null;function cats(){return skey()==='calender'?calCats:baseCats}function title(c){return c[1][lang==='he'?1:lang==='en'?2:0]}function rows(cat){return ((D[skey()]||{})[cat]||[])}
 function render(){if(!isE5())return;let p=document.getElementById('extruderSectionPage');if(!p||!p.classList.contains('active'))return;let old=document.getElementById('e5StationCatalog');if(old)old.remove();let d=document.createElement('div');d.id='e5StationCatalog';let cs=cats();if(selected){let c=cs.find(z=>z[0]===selected),r=rows(selected);d.innerHTML='<h2>'+x(sname())+'</h2>'+(skey()==='calender'?'<div class="e5st-location">'+tx('CK1 — локальный электрический шкаф каландера. Шкафное оборудование и полевое оборудование участка разделены.','CK1 — ארון החשמל המקומי של הקלנדר. ציוד הארון וציוד השטח מופרדים.','CK1 — local calender electrical cabinet. Cabinet equipment and field equipment are separated.')+'</div>':'')+'<div class="e5st-detail"><div class="e5st-head"><h3>'+x(title(c))+'</h3><button class="e5st-back" id="e5stBack">'+tx('Назад','חזור','Back')+'</button></div><div class="e5st-wrap"><table class="e5st-table"><thead><tr><th>'+tx('Название','שם','Name')+'</th><th>'+tx('Номер на чертеже','מספר בשרטוט','Drawing designation')+'</th><th>'+tx('Производитель','יצרן','Manufacturer')+'</th><th>Part No. / '+tx('модель','דגם','model')+'</th><th>'+tx('Данные','נתונים','Data')+'</th></tr></thead><tbody>'+(r.length?r.map(a=>'<tr>'+a.map(v=>'<td>'+x(v)+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="5">'+tx('Пока нет подтверждённых позиций из чертежей.','עדיין אין פריטים מאומתים מהשרטוטים.','No verified drawing items yet.')+'</td></tr>')+'</tbody></table></div></div>';p.appendChild(d);document.getElementById('e5stBack').onclick=e=>{e.stopPropagation();selected=null;render()};return}d.innerHTML='<h2>'+x(sname())+'</h2>'+(skey()==='calender'?'<div class="e5st-location">'+tx('CK1 — электрический шкаф каландера. Ниже отдельно: оборудование внутри шкафа и оборудование самого участка.','CK1 — ארון החשמל של הקלנדר. למטה: ציוד בתוך הארון וציוד השטח בנפרד.','CK1 — calender electrical cabinet. Cabinet equipment and field equipment are separated below.')+'</div>':'')+'<div class="e5st-grid">'+cs.map(c=>'<button type="button" class="e5st-tile" data-e5st="'+c[0]+'">'+x(title(c))+'</button>').join('')+'</div>';p.appendChild(d);d.querySelectorAll('[data-e5st]').forEach(b=>b.onclick=e=>{e.stopPropagation();selected=b.dataset.e5st;render()})}
 let f=window.openExtruderSection;if(typeof f==='function'&&!f.__e5stations){window.openExtruderSection=function(i){selected=null;let r=f.apply(this,arguments);setTimeout(render,80);setTimeout(render,260);return r};window.openExtruderSection.__e5stations=true}document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setTimeout(render,100)));
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
