def apply(legacy):
    patch = r'''<style>
/* A8 — fully isolated Extruder 5 / Extruder B mini-program. */
#extruderSectionPage.e5-exb-private > *{display:none!important}
#extruderSectionPage.e5-exb-private > #e5ExBPrivate{display:block!important}
#e5ExBPrivate{margin:10px 0 20px;padding:15px;border:2px solid #9fb8ba;border-radius:14px;background:#fff}
.e5xb-grid{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:12px}.e5xb-tile{min-height:82px;border:1px solid #cbd8d9;border-radius:11px;background:#f4f8f7;color:#34454b;font-size:14px;font-weight:700;padding:12px;cursor:pointer}.e5xb-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.e5xb-back{padding:8px 12px;border:1px solid #cbd8d9;border-radius:8px;background:#f4f8f7;cursor:pointer;font-weight:700}.e5xb-sub{font-size:12px;color:#687b80;margin:5px 0 12px}.e5xb-wrap{overflow:auto;max-height:650px}.e5xb-table{width:100%;border-collapse:collapse;min-width:900px}.e5xb-table th,.e5xb-table td{padding:8px;border-bottom:1px solid #e3eaea;text-align:left;font-size:12px;vertical-align:top}.e5xb-table th{position:sticky;top:0;background:#e8f1ef}@media(max-width:850px){.e5xb-grid{grid-template-columns:repeat(2,minmax(130px,1fr))}}
</style><script>
(function(){
 function tx(ru,he,en){return lang==='he'?he:lang==='en'?en:ru}
 function esc(s){return String(s==null?'':s).replace(/[&<>\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]})}
 function target(si){try{var mi=Number(currentMachineIndex),s=si==null?Number(currentExtruderSection):Number(si);if(mi===16&&s===2)return true;var mn=((machines[lang]||[])[mi]||'').toLowerCase(),sn=((extruderSections[lang]||[])[s]||'').toLowerCase();return mn.indexOf('5')>=0&&(mn.indexOf('экструдер')>=0||mn.indexOf('אקסטרודר')>=0||mn.indexOf('extruder')>=0)&&(sn.indexOf(' b')>=0||sn.indexOf(' b ')>=0||sn.indexOf('экструдер b')>=0||sn.indexOf('extruder b')>=0)}catch(e){return false}}
 var cats=[['cb1heat',['CB1 — нагрев цилиндра','CB1 — חימום צילינדר','CB1 — barrel heating']],['cb1aux',['CB1 — смазка / термостатирование','CB1 — סיכה / תרמוסטט','CB1 — lubrication / thermostatic unit']],['cb1io',['CB1 — PLC / I/O / Safety','CB1 — PLC / I/O / Safety','CB1 — PLC / I/O / Safety']],['cb3screen',['CB3 — сменщик фильтра','CB3 — מחליף מסנן','CB3 — screenchanger']],['cb3pump',['CB3 — насос расплава / трубы','CB3 — משאבת התך / צנרת','CB3 — melt pump / pipes']],['cb3heat',['CB3 — нагреватели / термопары','CB3 — גופי חימום / תרמוקפלים','CB3 — heaters / thermocouples']],['cb4vac',['CB4 — вакуумные насосы','CB4 — משאבות ואקום','CB4 — vacuum pumps']],['cb4valves',['CB4 — электроклапаны / охлаждение','CB4 — שסתומים חשמליים / קירור','CB4 — solenoid valves / cooling']],['field',['Моторы / датчики / полевое оборудование','מנועים / חיישנים / ציוד שטח','Motors / sensors / field equipment']]];
 function row(n,d,m,p,x){return[n,d,m,p,x]}
 var D={
 cb1heat:[row('Зона нагрева цилиндра 1','401','','','CB1'),row('Зона нагрева цилиндра 2','402','','','CB1'),row('Зона нагрева цилиндра 3','403','','','CB1'),row('Зона нагрева цилиндра 4','404','','','CB1'),row('Зона нагрева цилиндра 5','405','','','CB1'),row('Зона нагрева цилиндра 6','406','','','CB1'),row('Зона нагрева цилиндра 7','407','','','CB1'),row('Зона нагрева цилиндра 8','408','','','CB1'),row('Зона нагрева цилиндра 9','409','','','CB1'),row('Зона нагрева цилиндра 10','410','','','CB1'),row('Зона нагрева цилиндра 11','411','','','CB1'),row('Зона нагрева цилиндра 12','412','','','CB1'),row('Зона дегазации 1','413','','','CB1'),row('Зона дегазации 2','414','','','CB1'),row('SSR зоны адаптера сменщика фильтра','-415KP2','Carlo Gavazzi','RGS1A60D50KKE','50A 24Vdc'),row('Нагреватели адаптера','-415R2 / -415R2.1 / -415R2.2 / -415R2.3','','','4kW group'),row('Предохранитель нагрева','-415FU2','','5017906.25','25A gR')],
 cb1aux:[row('Пускатель насоса смазки','-85Q1','Siemens','3RA6120-2CB32','1–4A Class 10'),row('Мотор насоса смазки','+EB-85M1','','','Extruder lubrication pump'),row('MIN давление смазки','+EB-85SP5','','','Pressure sensor/switch'),row('MAX давление смазки','+EB-85SP6','','','Pressure sensor/switch'),row('Термостатическая установка цилиндра','+TU','','','Cylinder thermostatic unit'),row('Термопара термостатической установки','+TU-X1','','','IW1094')],
 cb1io:[row('DI 8x24VDC ST','-952A0','Siemens','6ES7131-6BF00-0BA0','ET200SP'),row('F-DQ 4x24VDC/2A PM HF','-962A0','Siemens','6ES7136-6DB00-0CA0','ET200SP'),row('AI Energy Meter ST','-907A0','Siemens','6ES7134-6PA00-0BD0','Heating supply measurement'),row('Контактор питания нагрева','-400KM7','Siemens','3RT1456-6AB36','275A 24Vdc S6')],
 cb3screen:[row('Узел сменщика фильтра','91 / 92','','','CB3'),row('Контроль температуры сменщика фильтра','93','','','CB3'),row('Контроль давления сменщика фильтра','94','','','CB3'),row('AI RTD/TC','-925A0','Siemens','6ES7134-6JF00-0CA1','ET200SP')],
 cb3pump:[row('Контроль температуры трубы','95','','','CB3'),row('Давление на входе насоса расплава','96','','','CB3'),row('Зона трубы 2','410','','','CB3'),row('Зона трубы 3','411','','','CB3'),row('Зона трубы 4','412','','','CB3'),row('Зона трубы 5','413','','','CB3'),row('Зона трубы 6','414','','','CB3'),row('Зона трубы 7','415','','','CB3'),row('Зона трубы 8','416','','','CB3'),row('Зона трубы 9','417','','','CB3')],
 cb3heat:[row('AI RTD/TC','-924A0','Siemens','6ES7134-6JF00-0CA1','ET200SP thermocouples'),row('Термопара pipe zone 4','+PB-412ST5','','','IW1576'),row('Термопара pipe zone 5','+PB-413ST5','','','IW1578'),row('Термопара pipe zone 6','+PB-414ST5','','','IW1580'),row('Термопара pipe zone 7','+PB-415ST5','','','IW1582'),row('Термопара pipe zone 8','+PB-416ST5','','','IW1584'),row('Термопара pipe zone 9','+PB-417ST5','','','IW1586')],
 cb4vac:[row('Вакуумные насосы','105 / 106','','','CB4'),row('Температура воды дегазации','109','','','CB4'),row('Остаточный вакуум дегазации','110','','','CB4'),row('Температура воздуха','110a','','','CB4'),row('Пуск/стоп вакуумных насосов','110b','','','CB4')],
 cb4valves:[row('Электроклапаны заполнения','107','','','CB4'),row('Электроклапаны срыва вакуума','108','','','CB4'),row('Bypass уровней дегазации','110c','','','CB4'),row('Охлаждение шкафа CB1','10','','','Cabinet cooling'),row('Охлаждение шкафа CB3','10','','','Cabinet cooling')],
 field:[row('Главный узел Extruder B','+EB','Bandera','2C85','Extruder B'),row('Главный мотор / шнек Extruder B','+EB','','','Main extrusion drive / screw'),row('Насос расплава B','+PB','','','Melt/volumetric pump'),row('Охлаждение цилиндра','','','','Cylinder cooling fans'),row('Датчик муфты ограничения момента','','','','Torque limiting coupling sensor')]
 };
 var selected=null;
 function label(c){return c[1][lang==='he'?1:lang==='en'?2:0]}
 function cleanup(){var x=document.getElementById('e5ExBPrivate');if(x)x.remove();var p=document.getElementById('extruderSectionPage');if(p)p.classList.remove('e5-exb-private')}
 function render(){var p=document.getElementById('extruderSectionPage');if(!p||!p.classList.contains('active')||!target()){cleanup();return}p.classList.add('e5-exb-private');var d=document.getElementById('e5ExBPrivate');if(!d){d=document.createElement('div');d.id='e5ExBPrivate';p.appendChild(d)}
 if(selected){var c=cats.find(function(x){return x[0]===selected}),rows=D[selected]||[];d.innerHTML='<div class="e5xb-head"><h2>'+esc(label(c))+'</h2><button class="e5xb-back" id="e5xbCatBack">'+tx('← Назад','← חזרה','← Back')+'</button></div><div class="e5xb-sub">S.3909 · OR16/268 · Extruder B · CB1 / CB3 / CB4</div><div class="e5xb-wrap"><table class="e5xb-table"><thead><tr><th>'+tx('Название','שם','Name')+'</th><th>'+tx('Номер на чертеже','מספר בשרטוט','Drawing designation')+'</th><th>'+tx('Производитель','יצרן','Manufacturer')+'</th><th>Part No.</th><th>'+tx('Данные','נתונים','Data')+'</th></tr></thead><tbody>'+rows.map(function(r){return '<tr>'+r.map(function(v){return '<td>'+esc(v)+'</td>'}).join('')+'</tr>'}).join('')+'</tbody></table></div>'}else{d.innerHTML='<button class="e5xb-back" id="e5xbMainBack">'+tx('← Назад','← חזרה','← Back')+'</button><h2>'+tx('Экструдер B — электрическое оборудование','אקסטרודר B — ציוד חשמלי','Extruder B — electrical equipment')+'</h2><div class="e5xb-sub">S.3909 · CB1 основной ящик · CB3 screenchanger + melt pump + pipes · CB4 vacuum pumps</div><div class="e5xb-grid">'+cats.map(function(c){return '<button class="e5xb-tile" data-e5xb="'+c[0]+'">'+esc(label(c))+'</button>'}).join('')+'</div>'}
 d.querySelectorAll('[data-e5xb]').forEach(function(b){b.onclick=function(e){e.preventDefault();e.stopPropagation();selected=this.dataset.e5xb;render()}});var b=document.getElementById('e5xbCatBack');if(b)b.onclick=function(e){e.preventDefault();e.stopPropagation();selected=null;render()};b=document.getElementById('e5xbMainBack');if(b)b.onclick=function(e){e.preventDefault();e.stopPropagation();cleanup();if(typeof openExtruder==='function')openExtruder(currentMachineIndex)}}
 var prev=window.openExtruderSection;if(typeof prev==='function'&&!prev.__e5xbPrivateA8){window.openExtruderSection=function(i){var t=target(i);selected=null;if(!t){cleanup();return prev.apply(this,arguments)}var r=prev.apply(this,arguments);/* remove the legacy section visually and mount one private module after legacy navigation has settled */setTimeout(render,0);return r};window.openExtruderSection.__e5xbPrivateA8=true}
 document.querySelectorAll('.lang button').forEach(function(b){b.addEventListener('click',function(){if(target())setTimeout(render,0)})});
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
