def apply(legacy):
    patch = r'''<style>
/* A10 — isolated Extruder 5 / Dosing system (Doteco Gravifeed K6). */
#extruderSectionPage.e5-dose-private > *{display:none!important}
#extruderSectionPage.e5-dose-private > #e5DosePrivate{display:block!important}
#e5DosePrivate{margin:10px 0 20px;padding:15px;border:2px solid #9fb8ba;border-radius:14px;background:#fff}.e5ds-grid{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:12px}.e5ds-tile{min-height:82px;border:1px solid #cbd8d9;border-radius:11px;background:#f4f8f7;color:#34454b;font-size:14px;font-weight:700;padding:12px;cursor:pointer}.e5ds-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.e5ds-back{padding:8px 12px;border:1px solid #cbd8d9;border-radius:8px;background:#f4f8f7;cursor:pointer;font-weight:700}.e5ds-sub{font-size:12px;color:#687b80;margin:5px 0 12px}.e5ds-wrap{overflow:auto;max-height:650px}.e5ds-table{width:100%;border-collapse:collapse;min-width:1000px}.e5ds-table th,.e5ds-table td{padding:8px;border-bottom:1px solid #e3eaea;text-align:left;font-size:12px;vertical-align:top}.e5ds-table th{position:sticky;top:0;background:#e8f1ef}@media(max-width:850px){.e5ds-grid{grid-template-columns:repeat(2,minmax(130px,1fr))}}
</style><script>
(function(){
 function tx(ru,he,en){return lang==='he'?he:lang==='en'?en:ru}function esc(s){return String(s==null?'':s).replace(/[&<>\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]})}
 function target(si){try{var mi=Number(currentMachineIndex),s=si==null?Number(currentExtruderSection):Number(si);if(mi===16&&s===0)return true;var mn=((machines[lang]||[])[mi]||'').toLowerCase(),sn=((extruderSections[lang]||[])[s]||'').toLowerCase();return mn.indexOf('5')>=0&&(mn.indexOf('экструдер')>=0||mn.indexOf('אקסטרודר')>=0||mn.indexOf('extruder')>=0)&&(sn.indexOf('доз')>=0||sn.indexOf('מינון')>=0||sn.indexOf('dosing')>=0)}catch(e){return false}}
 var cats=[['id',['Паспорт системы','זיהוי המערכת','System identification']],['control',['Контроллер / интерфейс / I/O','בקר / ממשק / I/O','Controller / interface / I/O']],['feeders',['Дозаторы / моторы / энкодеры','מזינים / מנועים / אנקודרים','Feeders / motors / encoders']],['weight',['Тензодатчики / взвешивание','תאי שקילה / שקילה','Load cells / weighing']],['valves',['Клапаны / пневматика / уровни','שסתומים / פנאומטיקה / מפלסים','Valves / pneumatics / levels']],['power',['Питание / защита / шкаф','הזנה / הגנות / ארון','Power / protection / cabinet']],['wiring',['Разъёмы / клеммы / связи','מחברים / מהדקים / תקשורת','Connectors / terminals / communications']],['maintenance',['Запчасти / обслуживание','חלפים / תחזוקה','Spares / maintenance']]];
 function row(n,d,m,p,x){return[n,d,m,p,x]}var D={
 id:[row('Гравиметрическая система дозирования','','DOTECO','GRAVIFEED K6','Line 5 · MAT CM21000037 · S/N SN00003702 · Year 2010'),row('Auger dosing station kit','','DOTECO','MGRF00901EN','Screw/auger dosing station for Gravifeed'),row('Производитель','','DOTECO S.p.A.','','San Martino Spino, Modena, Italy')],
 control:[row('Основной контроллер Gravifeed','','DOTECO','GRAVIFEED K6','Microprocessor continuously acquires hopper weight and regulates feeder screw speed'),row('Операторская панель / HMI','','DOTECO','','Touch-screen/operator interface shown in electrical drawings'),row('Контроллеры дозирующих каналов','','DOTECO','','Multiple feeder channels shown in electrical drawings'),row('Цифровые входы/выходы','','DOTECO','','Machine I/O shown on wiring diagrams; preserve wiring drawing as authority'),row('Связь с внешней системой','','DOTECO','','Communication/interface wiring shown in electrical drawings')],
 feeders:[row('Наклонный шнековый дозатор','','DOTECO','','Feeding screw / auger; diameter and pitch depend on required throughput'),row('DC мотор-редуктор дозатора','','DOTECO','','DC gearmotor; speed is regulated by dosing controller'),row('Щётки двигателя','','DOTECO','','Maintenance item: inspect every 6 months'),row('Энкодер дозатора','','DOTECO','','Feeder encoder; encoder brushes are maintenance item'),row('Щётки энкодера','','DOTECO','','Maintenance inspection item'),row('Редуктор дозатора','','DOTECO','','Check gearbox for leaks; Varvel Viton oil seals specified for replacement'),row('Шнек 15x10','','DOTECO','15x10','PP average throughput 0.250–48.217 kg/h'),row('Шнек 15x15','','DOTECO','15x15','PP average throughput 0.433–73.588 kg/h'),row('Шнек 20x20','','DOTECO','20x20','PP average throughput 1.112–186.066 kg/h'),row('Шнек 25x25','','DOTECO','25x25','PP average throughput 1.714–307.902 kg/h'),row('Шнек 30x30','','DOTECO','30x30','PP average throughput 2.775–498.566 kg/h')],
 weight:[row('Тензодатчик бункера','','DOTECO','','Off-center load cell; each feed hopper bears completely on one load cell'),row('Сигнал веса','','DOTECO','','Load-cell signal proportional to hopper weight; continuously acquired by controller'),row('Калибровка тензодатчика','','DOTECO','','Check every 15 days with known sample weight; calibrate if measured value differs')],
 valves:[row('Butterfly valve / заслонка загрузки','','DOTECO','','Pneumatic cylinder operated; opens automatically at minimum material weight'),row('Пневмоцилиндр заслонки','','DOTECO','','Actuator for butterfly/refill valve'),row('Ручная шиберная заслонка','','DOTECO','','Manual slide gate'),row('Датчик уровня pre-storage hopper','','DOTECO','','Capacitive level sensor; maintenance check specified'),row('Pre-storage hopper','','DOTECO','','Optional component')],
 power:[row('Электрический шкаф Gravifeed','','DOTECO','','Electrical cabinet shown in wiring drawings'),row('Главный выключатель / питание','','DOTECO','','Main power supply and auxiliary circuit shown in wiring drawings'),row('24 VDC / вспомогательное питание','','DOTECO','','Control power distribution shown in wiring drawings'),row('Защитные аппараты','','DOTECO','','Fuses/breakers shown in electrical material list and power diagrams')],
 wiring:[row('Клеммные колодки','','DOTECO','','Terminal blocks and external connections shown in wiring drawings'),row('Разъёмы дозирующих станций','','DOTECO','','Individual feeder/station connectors shown in wiring diagrams'),row('Разъёмы тензодатчиков','','DOTECO','','Load-cell wiring shown in dedicated diagram'),row('Разъёмы мотор/энкодер','','DOTECO','','Motor and encoder wiring shown for individual feeders')],
 maintenance:[row('Load cells','','DOTECO','','Check every 15 days'),row('Butterfly valve','','DOTECO','','Check correct operation'),row('Motor brushes','','DOTECO','','Check every 6 months; replace if excessive wear'),row('Encoder brushes','','DOTECO','','Periodic inspection'),row('Gearbox oil seals','','Varvel','Viton oil seals','Specified replacement seals'),row('Feeding screw bushings','','DOTECO','','Inspect screw enclosure and bronze bushings for wear'),row('Half-couplings','','DOTECO','','Inspect feeder screw / gearbox half-couplings for wear'),row('Capacitive level sensors','','DOTECO','','Check correct operation')]
 };
 var selected=null;function label(c){return c[1][lang==='he'?1:lang==='en'?2:0]}function cleanup(){var x=document.getElementById('e5DosePrivate');if(x)x.remove();var p=document.getElementById('extruderSectionPage');if(p)p.classList.remove('e5-dose-private')}
 function render(){var p=document.getElementById('extruderSectionPage');if(!p||!p.classList.contains('active')||!target()){cleanup();return}p.classList.add('e5-dose-private');var d=document.getElementById('e5DosePrivate');if(!d){d=document.createElement('div');d.id='e5DosePrivate';p.appendChild(d)}if(selected){var c=cats.find(function(x){return x[0]===selected}),rows=D[selected]||[];d.innerHTML='<div class="e5ds-head"><h2>'+esc(label(c))+'</h2><button class="e5ds-back" id="e5dsCatBack">'+tx('← Назад','← חזרה','← Back')+'</button></div><div class="e5ds-sub">Extruder 5 · DOTECO GRAVIFEED K6 · CM21000037 · SN00003702</div><div class="e5ds-wrap"><table class="e5ds-table"><thead><tr><th>'+tx('Название','שם','Name')+'</th><th>'+tx('Номер на чертеже','מספר בשרטוט','Drawing designation')+'</th><th>'+tx('Производитель','יצרן','Manufacturer')+'</th><th>Part No.</th><th>'+tx('Данные','נתונים','Data')+'</th></tr></thead><tbody>'+rows.map(function(r){return '<tr>'+r.map(function(v){return '<td>'+esc(v)+'</td>'}).join('')+'</tr>'}).join('')+'</tbody></table></div>'}else{d.innerHTML='<button class="e5ds-back" id="e5dsMainBack">'+tx('← Назад','← חזרה','← Back')+'</button><h2>'+tx('Система дозирования — DOTECO GRAVIFEED K6','מערכת מינון — DOTECO GRAVIFEED K6','Dosing system — DOTECO GRAVIFEED K6')+'</h2><div class="e5ds-sub">MAT CM21000037 · S/N SN00003702 · 2010</div><div class="e5ds-grid">'+cats.map(function(c){return '<button class="e5ds-tile" data-e5ds="'+c[0]+'">'+esc(label(c))+'</button>'}).join('')+'</div>'}d.querySelectorAll('[data-e5ds]').forEach(function(b){b.onclick=function(e){e.preventDefault();e.stopPropagation();selected=this.dataset.e5ds;render()}});var b=document.getElementById('e5dsCatBack');if(b)b.onclick=function(e){e.preventDefault();e.stopPropagation();selected=null;render()};b=document.getElementById('e5dsMainBack');if(b)b.onclick=function(e){e.preventDefault();e.stopPropagation();cleanup();if(typeof openExtruder==='function')openExtruder(currentMachineIndex)}}
 var prev=window.openExtruderSection;if(typeof prev==='function'&&!prev.__e5doseA10){window.openExtruderSection=function(i){var t=target(i);selected=null;if(!t){cleanup();return prev.apply(this,arguments)}var r=prev.apply(this,arguments);setTimeout(render,0);return r};window.openExtruderSection.__e5doseA10=true}document.querySelectorAll('.lang button').forEach(function(b){b.addEventListener('click',function(){if(target())setTimeout(render,0)})});
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
