def apply(legacy):
    patch = r'''<style>
#e5StationCatalog{margin:14px 0 20px;padding:15px;border:1px solid #d3ddde;border-radius:14px;background:#fff}.e5st-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px}.e5st-tile{min-height:72px;border:1px solid #cbd8d9;border-radius:11px;background:#f8fbfa;color:#34454b;font-size:15px;font-weight:700;padding:12px;cursor:pointer}.e5st-detail{margin-top:14px;border:1px solid #cbd8d9;border-radius:12px;padding:14px}.e5st-wrap{overflow:auto;max-height:580px}.e5st-table{width:100%;border-collapse:collapse;min-width:900px}.e5st-table th,.e5st-table td{padding:8px;border-bottom:1px solid #e3eaea;text-align:left;font-size:12px;vertical-align:top}.e5st-table th{position:sticky;top:0;background:#f4f8f7}.e5st-head{display:flex;justify-content:space-between;align-items:center}.e5st-back{padding:7px 11px;border:1px solid #cbd8d9;border-radius:8px;background:#f4f8f7;cursor:pointer}@media(max-width:850px){.e5st-grid{grid-template-columns:repeat(2,minmax(140px,1fr))}}
</style><script>
(function(){
 function tx(a,b,c){return lang==='he'?b:lang==='en'?c:a} function x(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
 function isE5(){let n=((machines[lang]||[])[currentMachineIndex]||'').toLowerCase();return n.includes('5')&&(n.includes('экструдер')||n.includes('אקסטרודר')||n.includes('extruder'))}
 function sname(){return ((extruderSections[lang]||[])[currentExtruderSection]||'')}
 function skey(){let s=sname().toLowerCase();if((s.includes('extruder a')||s.includes('экструдер a')||s.includes('אקסטרודר a')||s.includes('משני')))return'a';if((s.includes('extruder b')||s.includes('экструдер b')||s.includes('אקסטרודר b')||s.includes('ראשי')))return'b';if(s.includes('cal')||s.includes('кал')||s.includes('קלנ'))return'calender';if(s.includes('wind')||s.includes('намот')||s.includes('גליל'))return'winding';if(s.includes('sil')||s.includes('силик')||s.includes('סיליק'))return'silicone';return'other'}
 const cats=[['drives',['Драйверы','דרייבים','Drives']],['motors',['Моторы','מנועים','Motors']],['starters',['Пускатели / защита','מתנעים / הגנה','Starters / protection']],['contactors',['Контакторы','קונטקטורים','Contactors']],['relays',['Реле','ממסרים','Relays']],['io',['PLC / I/O','PLC / I/O','PLC / I/O']],['sensors',['Датчики','חיישנים','Sensors']],['valves',['Клапаны / пневматика','שסתומים / פנאומטיקה','Valves / pneumatics']],['heating',['Нагрев','חימום','Heating']],['other',['Прочее','אחר','Other']]];
 const D={
  a:{drives:[['Главный привод Extruder A','-41U2','ABB','ACS880-01-169A-3','90 kW · 400 V · IP21']],motors:[['Мотор Extruder A','-41M2','ABB','M3BP 280SMB','90 kW · 160 A · 400 V · 50 Hz · 1483 rpm']],heating:[['Терморегуляция зон Extruder A','401–408','', '', 'Zones 0–4 + spare; heating circuits'],['Статическое реле нагрева','-404KP2 / -405KP2 / -408KP2','Carlo Gavazzi','RGS1A60D50KKE','50 A · 24 VDC']],starters:[['Прямой пускатель','-404Q6 / -405Q6','Siemens','3RM1002-2AA04','0.4–2 A']],valves:[['Соленоид клапана головки Extruder A','46','', '', 'Hub solenoid valve']],io:[['ET200SP interface','-906A1','Siemens','6ES7155-6AU00-0CN0','IM155-6 PN HF'],['AQ module','-933A0','Siemens','6ES7135-6HD00-0BA1','AQ 4xU/I ST; pump speed regulation'],['F-DQ','-963A0','Siemens','6ES7136-6DB00-0CA0','F-DQ 4x24VDC/2A PM HF']]},
  b:{drives:[['Главный привод Extruder B','-81U2','ABB','ACS880-04-585A-3','315 kW · 400 V · IP20'],['Привод насоса Extruder B','-101U2','ABB','ACS880-01-045A-3','22 kW · 400 V · IP21']],motors:[['Вакуумный насос 1','-105M1','', '', '11 kW · 21.1 A · 380 V · 50 Hz'],['Вакуумный насос 2','-105M6','', '', '11 kW · 21.1 A · 380 V · 50 Hz']],starters:[['Компактный пускатель вакуумного насоса','-105Q1 / -105Q6 / -106Q1','Siemens','3RA6120-2EB32','24 VDC · 8–32 A · CLASS 10']],heating:[['Терморегуляция Extruder B / screenchanger / pipes','93–97 / 410–417','', '', 'Temperature and pressure control zones']],sensors:[['Мин. уровень воды дегазации','+VB-107SL6','', '', 'Degassing water tank min level'],['Макс. уровень воды дегазации','+VB-107SL7','', '', 'Degassing water tank max level'],['Макс. уровень конденсата','+VB-107SL8','', '', 'Degassing condensate max level']],valves:[['Клапаны заполнения','107','', '', 'Refilling solenoid valves'],['Клапаны сброса вакуума','108','', '', 'Vacuum break solenoid valves']],io:[['DI module','-952A0','Siemens','6ES7131-6BF00-0BA0','DI 8x24VDC ST ET200SP'],['F-DQ','-962A0','Siemens','6ES7136-6DB00-0CA0','F-DQ 4x24VDC/2A PM HF']]},
  calender:{drives:[['Drive','-685U1','ABB','ACS355-03E-01A2-4','Frame R0'],['Wedge drive','-711U1 / -715U1 / -721U1 / -725U1','ABB','BSD0200','0.2 kW axes'],['Translation drive','-751U1','ABB','ACS355-03E-01A9-4','Frame R0']],motors:[['Inlet left wedge motor','-711M1','ABB','BSM0200CN00','0.2 kW · 1.5 A · 91 V · 200 Hz · 3000 rpm'],['Outlet left wedge motor','-721M1','ABB','BSM0200CN00','0.2 kW · 1.5 A · 91 V · 200 Hz · 3000 rpm'],['Hydraulic unit pump motor','-761M1','', '', 'Calender oleodynamic unit']],starters:[['Reversing starter','-675Q1 / -678Q1','Siemens','3RM1302-2AA04','0.4–2.0 A failsafe'],['Reversing starter','-755Q1','Siemens','3RM1307-2AA04','1.6–7.0 A failsafe'],['Motor protection','-761QM1','Siemens','3RV2011-1JA20 / 3RV2011-1HA20','7–10 A / 5.5–8 A']],contactors:[['Contactor','-710KM4 / -710KM5','Siemens','3RT2025-2BB40','7.5 kW · 24 VDC · S0'],['Contactor','-761KM3','Siemens','3RT2016-2BB41','4 kW · 24 VDC · S00']],sensors:[['Haul-off load cell','791 / 1120','', '', 'Load cell'],['Material temperature pyrometer','793','', '', 'Pyrometer'],['Roll pressure','768','', '', 'Pressure measurement']],valves:[['Hydraulic solenoid valves','763–765','', '', 'Calender oleodynamic unit']],io:[['AQ module','-932A0','Siemens','6ES7135-6HD00-0BA1','AQ 4xU/I ST ET200SP'],['DI module','-959A0','Siemens','6ES7131-6BF60-0AA0','DI 8x24VDC SCR BA'],['DQ module','-976A0','Siemens','6ES7132-6BF60-0AA0','DQ 8x24VDC/0.5A SINK BA']]},
  winding:{drives:[['Trim winder drive','-862U1 / -866U1','ABB','ACS550-01-04A1-4','1.5 kW'],['Unwinder drive','-872U2 / -876U2','ABB','ACS880-01-05A6-3','Profinet via FENA-11']],motors:[['Unwinder motor 1','1104','', '', 'Unwinder 1'],['Unwinder motor 2','1105','', '', 'Unwinder 2']],io:[['Operator panel','201–202','', '', 'Unwinder control panel'],['PLC / safe I/O','901 / 906 / 927 / 928 / 931 / 932 / 941 / 942 / 943 / 952–954 / 961–962 / 971–972','Siemens','','Unwinder control and safe I/O']],sensors:[['Take-off load cell','792','', '', 'Siliconator take-off load cell']]},
  silicone:{sensors:[['Take-off load cell','792','', '', 'Siliconator take-off load cell']],other:[['Unwinder control interface','1101–1103','', '', 'Interface / supply associated with unwinder section']]},
  other:{other:[['Head box','CT1','', '', 'Head/feedblock thermoregulation and screenchanger interface'],['Trim suction box','CV1','', '', 'Trim suction motor and auxiliary circuit'],['Control desk','C30','', '', 'Operator panels, PLC I/O, emergency and auxiliary circuits']]}
 };
 let selected=null;function title(c){return c[1][lang==='he'?1:lang==='en'?2:0]}
 function rows(cat){return ((D[skey()]||{})[cat]||[])}
 function render(){if(!isE5())return;let p=document.getElementById('extruderSectionPage');if(!p||!p.classList.contains('active'))return;let old=document.getElementById('e5StationCatalog');if(old)old.remove();let d=document.createElement('div');d.id='e5StationCatalog';if(selected){let c=cats.find(z=>z[0]===selected),r=rows(selected);d.innerHTML='<h2>'+x(sname())+'</h2><div class="e5st-detail"><div class="e5st-head"><h3>'+x(title(c))+'</h3><button class="e5st-back" id="e5stBack">'+tx('Назад','חזור','Back')+'</button></div><div class="e5st-wrap"><table class="e5st-table"><thead><tr><th>'+tx('Название','שם','Name')+'</th><th>'+tx('Номер на чертеже','מספר בשרטוט','Drawing designation')+'</th><th>'+tx('Производитель','יצרן','Manufacturer')+'</th><th>Part No. / '+tx('модель','דגם','model')+'</th><th>'+tx('Данные','נתונים','Data')+'</th></tr></thead><tbody>'+(r.length?r.map(a=>'<tr>'+a.map(v=>'<td>'+x(v)+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="5">'+tx('Пока нет подтверждённых позиций из чертежей.','עדיין אין פריטים מאומתים מהשרטוטים.','No verified drawing items yet.')+'</td></tr>')+'</tbody></table></div></div>';p.appendChild(d);document.getElementById('e5stBack').onclick=e=>{e.stopPropagation();selected=null;render()};return}d.innerHTML='<h2>'+x(sname())+'</h2><div class="e5st-grid">'+cats.map(c=>'<button type="button" class="e5st-tile" data-e5st="'+c[0]+'">'+x(title(c))+'</button>').join('')+'</div>';p.appendChild(d);d.querySelectorAll('[data-e5st]').forEach(b=>b.onclick=e=>{e.stopPropagation();selected=b.dataset.e5st;render()})}
 let f=window.openExtruderSection;if(typeof f==='function'&&!f.__e5stations){window.openExtruderSection=function(i){selected=null;let r=f.apply(this,arguments);setTimeout(render,80);setTimeout(render,260);return r};window.openExtruderSection.__e5stations=true}document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setTimeout(render,100)));
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
