def apply(legacy):
    patch = r'''<style>
.e4detailbox{margin:12px 0 18px;padding:14px;border:1px solid #cbd8d9;border-radius:12px;background:#fff}.e4detailbox h3{margin:0 0 10px;font-size:18px}.e4detailbox .close{margin-bottom:10px;padding:8px 12px;border:1px solid #b9c8ca;border-radius:8px;background:#eef5f3;cursor:pointer}.e4detailbox table{width:100%;border-collapse:collapse;min-width:900px}.e4detailbox-wrap{overflow:auto;max-height:520px}.e4detailbox th,.e4detailbox td{padding:8px 9px;border-bottom:1px solid #e3eaea;text-align:left;vertical-align:top}.e4detailbox th{position:sticky;top:0;background:#f7faf9;z-index:1;font-size:12px;color:#5b6d71}.e4draw-card{cursor:pointer}.e4draw-card:hover{box-shadow:0 2px 8px rgba(0,0,0,.10);transform:translateY(-1px)}
</style>
<script>
(function(){
 function tx(ru,he,en){return lang==='he'?he:lang==='en'?en:ru}
 function e(s){return (window.esc?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])))}
 function isE4(){let n=((machines[lang]||[])[currentMachineIndex]||'').toLowerCase();return n.includes('4')&&(n.includes('экструдер')||n.includes('אקסטרודר')||n.includes('extruder'))}
 function sectionKey(){let s=((extruderSections[lang]||[])[currentExtruderSection]||'').toLowerCase();if(s.includes('кал')||s.includes('קלנ')||s.includes('cal'))return'calender';if((s.includes('a')||s.includes('משני'))&&(s.includes('extr')||s.includes('אקס')))return'a';if((s.includes('b')||s.includes('ראשי'))&&(s.includes('extr')||s.includes('אקס')))return'b';return'other'}
 const data={
  calender:{
   drives:[
    {ru:'Привод входного валка',he:'דרייב גליל כניסה',en:'Inlet roll drive',d:'-91U1',model:'ABB ACS 800-01-0011-3',spec:'6.5 kW; Profibus ADD=70',qty:1},
    {ru:'Привод центрального валка',he:'דרייב גליל מרכזי',en:'Central roll drive',d:'-95U1',model:'ABB ACS 800-01-0020-3',spec:'12 kW; Profibus ADD=71',qty:1},
    {ru:'Привод выходного валка',he:'דרייב גליל יציאה',en:'Outlet roll drive',d:'-99U1',model:'ABB ACS 800-01-0011-3',spec:'6.5 kW; Profibus ADD=72',qty:1},
    {ru:'Привод перемещения каландра',he:'דרייב תנועת קלנדר',en:'Calender movement drive',d:'-110U1',model:'ABB ACS 550-01-03A3-4J-404',spec:'0.25 kW',qty:1},
    {ru:'Привод охлаждающего валка',he:'דרייב גליל קירור',en:'Cooling roll drive',d:'-120U1',model:'ABB ACS 800-01-0006-3',spec:'6.5 kW; Profibus ADD=73',qty:1},
    {ru:'Привод тянущего устройства',he:'דרייב משיכה',en:'Take-off drive',d:'-130U1',model:'ABB ACS 800-01-0005-3',spec:'2.7 kW; Profibus ADD=81',qty:1},
    {ru:'Привод прижимного валка',he:'דרייב גליל לחץ',en:'Pressure roll drive',d:'-145U1',model:'ABB ACS 550-01-03A3-4J-404',spec:'0.25 kW; Profibus ADD=75',qty:1}
   ],
   motors:[{ru:'Мотор входного валка',he:'מנוע גליל כניסה',en:'Inlet roll motor',d:'-91M1',model:'AX 100K.2',spec:'6.5 kW',qty:1},{ru:'Мотор центрального валка',he:'מנוע גליל מרכזי',en:'Central roll motor',d:'-95M1',model:'AX 100K.4',spec:'12 kW',qty:1},{ru:'Мотор выходного валка',he:'מנוע גליל יציאה',en:'Outlet roll motor',d:'-99M1',model:'AX 100K.2',spec:'6.5 kW',qty:1},{ru:'Мотор охлаждающего валка',he:'מנוע גליל קירור',en:'Cooling roll motor',d:'-120M1',model:'AX 80CS.2',spec:'6.5 kW',qty:1},{ru:'Мотор тянущего устройства',he:'מנוע משיכה',en:'Take-off motor',d:'-130M1',model:'AX 80CS.075',spec:'2.7 kW',qty:1}],
   fans:[{ru:'Вентилятор входного валка',he:'מאוורר גליל כניסה',en:'Inlet roll motor fan',d:'-94M1',model:'',spec:'0.075 kW',qty:1},{ru:'Вентилятор центрального валка',he:'מאוורר גליל מרכזי',en:'Central roll motor fan',d:'-98M1',model:'',spec:'0.075 kW',qty:1}],
   safety:[{ru:'Аварийная цепь каландра',he:'מעגל חירום קלנדר',en:'Calender emergency circuit',d:'',model:'Safety circuit',spec:'Emergency / gates / haul-off',qty:1}],
   hydraulics:[{ru:'Подъём / опускание каландра',he:'הרמה / הורדה קלנדר',en:'Calender up / down',d:'-112M1',model:'',spec:'1.8 kW',qty:1}],
   control:[{ru:'Управление каландром',he:'בקרת קלנדר',en:'Calender control',d:'',model:'PLC / I/O signals',spec:'Auxiliary circuits and control signals',qty:1}]
  },
  a:{drives:[{ru:'Привод экструдера A',he:'דרייב אקסטרודר A',en:'Extruder A drive',d:'-53U1',model:'ABB ACS 800-01-0100-3',spec:'75 kW; Profibus ADD=21',qty:1},{ru:'Привод объёмного насоса A',he:'דרייב משאבה נפחית A',en:'Volumetric pump A drive',d:'-38U1',model:'ABB ACS 800-01-0006-3',spec:'3.9 kW; Profibus ADD=26',qty:1}],motors:[{ru:'Мотор экструдера A',he:'מנוע אקסטרודר A',en:'Extruder A motor',d:'-53M1',model:'ABB M3AA 250 SMB',spec:'75 kW',qty:1},{ru:'Мотор объёмного насоса A',he:'מנוע משאבה נפחית A',en:'Volumetric pump A motor',d:'-38M1',model:'LENZE MCA 14L35',spec:'3.9 kW',qty:1}]},
  b:{drives:[{ru:'Привод экструдера B',he:'דרייב אקסטרודר B',en:'Extruder B drive',d:'-61U1',model:'ABB ACS 800-04-0400-3',spec:'315 kW; Profibus ADD=11',qty:1},{ru:'Привод объёмного насоса B',he:'דרייב משאבה נפחית B',en:'Volumetric pump B drive',d:'-43U1',model:'ABB ACS 800-01-0030-3',spec:'20.3 kW; Profibus ADD=16',qty:1}],motors:[{ru:'Мотор экструдера B',he:'מנוע אקסטרודר B',en:'Extruder B motor',d:'-61M1',model:'ABB M2BA 355 SMA4',spec:'315 kW',qty:1},{ru:'Мотор объёмного насоса B',he:'מנוע משאבה נפחית B',en:'Volumetric pump B motor',d:'-43M1',model:'LENZE MCA 21X35',spec:'20.3 kW',qty:1}]},
  main:{
   plc:[{ru:'Главный PLC CPU',he:'CPU ראשי של PLC',en:'Main PLC CPU',d:'-900U2',model:'Siemens CPU 317F-2 PN/DP',spec:'6ES7317-2FK14-0AB0',qty:1},{ru:'Карта памяти PLC',he:'כרטיס זיכרון PLC',en:'PLC memory card',d:'-900U2',model:'SIMATIC S7 Micro Memory Card 2 MB',spec:'6ES7953-8LL31-0AA0',qty:1}],
   io:[{ru:'Модуль интерфейса ET200S',he:'מודול ממשק ET200S',en:'ET200S interface module',d:'+2-206U1',model:'6ES7151-7FA20-0AB0',spec:'Siemens ET 200S',qty:1},{ru:'Модуль I/O',he:'מודול I/O',en:'I/O module',d:'+2-206U2',model:'6ES7138-4CB11-0AA0',spec:'Siemens',qty:1},{ru:'Модуль I/O',he:'מודול I/O',en:'I/O module',d:'+2-206U3',model:'6ES7138-4FA03-0AB0',spec:'Siemens',qty:1},{ru:'Модуль I/O',he:'מודול I/O',en:'I/O module',d:'+2-206U5',model:'6ES7138-4FB02-0AB0',spec:'Siemens',qty:1}],
   safety:[{ru:'Безопасный PLC / I/O модуль',he:'PLC / I/O בטיחות',en:'Safety PLC / I/O module',d:'+2-206U1',model:'6ES7151-7FA20-0AB0',spec:'Siemens safety station',qty:1}],
   power:[{ru:'Буферный модуль SITOP',he:'מודול גיבוי SITOP',en:'SITOP buffer module',d:'-5U1',model:'6EP1961-3BA01',spec:'Siemens',qty:1},{ru:'Блок питания SITOP PSU200M',he:'ספק SITOP PSU200M',en:'SITOP PSU200M power supply',d:'-5U2',model:'6EP1333-3BA10',spec:'5A',qty:1},{ru:'Трёхфазный блок питания 24VDC',he:'ספק תלת פאזי 24VDC',en:'Three-phase 24VDC power supply',d:'-21U1',model:'6EP1436-2BA10',spec:'400-500Vac / 24Vdc 20A',qty:1},{ru:'Модуль селективной защиты',he:'מודול הגנה סלקטיבית',en:'Selective protection module',d:'-21U3',model:'6EP1961-2BA21',spec:'SITOP PSE200U 10A',qty:1}],
   ethernet:[{ru:'Ethernet switch',he:'מתג Ethernet',en:'Ethernet switch',d:'-891U2',model:'Siemens SCALANCE XB008',spec:'6GK5008-0BA00-1AB2',qty:1},{ru:'Ethernet switch',he:'מתג Ethernet',en:'Ethernet switch',d:'-891U7',model:'Siemens SCALANCE XB008',spec:'6GK5008-0BA00-1AB2',qty:1},{ru:'Communication Processor CP343-1',he:'מעבד תקשורת CP343-1',en:'Communication Processor CP343-1',d:'-900U5',model:'Siemens CP343-1',spec:'Communication processor for SIMATIC S7-300',qty:1}],
   contactors:[{ru:'Контактор',he:'קונטקטור',en:'Contactor',d:'+2-36KM2',model:'Siemens 3RT1016-1AF01',spec:'Auxiliary 3RH1911-1FA11',qty:1},{ru:'Контактор',he:'קונטקטור',en:'Contactor',d:'+2-40KM1',model:'Siemens 3RT1016-1AF01',spec:'',qty:1},{ru:'Контактор',he:'קונטקטור',en:'Contactor',d:'+2-45KM1',model:'Siemens 3RT1035-1AG20',spec:'',qty:1},{ru:'Контактор',he:'קונטקטור',en:'Contactor',d:'+2-55KM2',model:'Siemens 3RT1446-1AG20',spec:'',qty:1},{ru:'Контактор',he:'קונטקטור',en:'Contactor',d:'+2-57KM4',model:'Siemens 3RT1025-1AG20',spec:'',qty:1},{ru:'Контактор',he:'קונטקטור',en:'Contactor',d:'+2-65KM4',model:'Siemens 3RT1026-1AG20',spec:'',qty:1}],
   relays:[{ru:'Промежуточное реле',he:'ממסר ביניים',en:'Interface relay',d:'+2-27KA7',model:'Phoenix Contact 2966171',spec:'',qty:1},{ru:'Промежуточное реле',he:'ממסר ביניים',en:'Interface relay',d:'+2-29KA7',model:'Phoenix Contact 2966171',spec:'',qty:1},{ru:'Реле',he:'ממסר',en:'Relay',d:'+2-29KA2',model:'Omron MY3 110VCA',spec:'',qty:1},{ru:'Реле',he:'ממסר',en:'Relay',d:'+2-29KA2',model:'Omron MY4-110V',spec:'',qty:1}],
   breakers:[{ru:'Главный автоматический выключатель',he:'מאמ״ת ראשי',en:'Main circuit breaker',d:'-5QF6',model:'Siemens 3WL1220-2BB44-1AJ2-Z T40',spec:'2000A 4P 66kA',qty:1},{ru:'Автоматический выключатель',he:'מאמ״ת',en:'Circuit breaker',d:'-8QF1',model:'Siemens 5SY8206-7',spec:'6A C 2P',qty:1},{ru:'УЗО / дифференциальный блок',he:'פחת',en:'RCD block',d:'-8QF1',model:'Siemens 5SM2322-0',spec:'30mA AC 2P 0.3-40A',qty:1},{ru:'Автоматический выключатель',he:'מאמ״ת',en:'Circuit breaker',d:'-21QF1',model:'Siemens 5SY8306-7',spec:'6A C 3P',qty:1}],
   sensors:[{ru:'Датчики / концевики по схеме',he:'חיישנים / מפסקי גבול לפי השרטוט',en:'Sensors / limit switches from drawing',d:'SQ / SP / B',model:'',spec:'Раздел будет наполняться по обозначениям из чертежа',qty:0}],
   signals:[{ru:'Сигнальная лампа / светильник',he:'נורית / תאורה',en:'Signal lamp / light',d:'-8HL1',model:'Sikur Italia COO7-50',spec:'7W',qty:1},{ru:'Сигнальная лампа',he:'נורית איתות',en:'Signal lamp',d:'-9HL2',model:'Sirena FLR90353',spec:'Red',qty:1}]
  }
 };
 function label(x){return x[lang]||x.ru||x.en||''}
 function renderRows(rows){return rows.map(x=>'<tr><td><b>'+e(label(x))+'</b></td><td><b>'+e(x.d||'—')+'</b></td><td>'+e(x.model||'—')+'</td><td>'+e(x.spec||'—')+'</td><td>'+e(x.qty??1)+'</td><td>0</td></tr>').join('')}
 function show(title,rows,host){let old=document.getElementById('e4AllDetail');if(old)old.remove();let d=document.createElement('div');d.id='e4AllDetail';d.className='e4detailbox';d.innerHTML='<button class="close">'+tx('← Закрыть','← סגור','← Close')+'</button><h3>'+e(title)+'</h3><div class="e4detailbox-wrap"><table><thead><tr><th>'+tx('Название','שם','Name')+'</th><th>'+tx('Номер на чертеже','מספר בשרטוט','Drawing designation')+'</th><th>'+tx('Модель / Part No.','דגם / מק״ט','Model / Part No.')+'</th><th>'+tx('Данные','נתונים','Data')+'</th><th>'+tx('На машине','במכונה','On machine')+'</th><th>'+tx('Склад','מחסן','Warehouse')+'</th></tr></thead><tbody>'+renderRows(rows)+'</tbody></table></div>';d.querySelector('.close').onclick=()=>d.remove();host.parentNode.insertBefore(d,host.nextSibling)}
 function classifyTitle(t){t=(t||'').toLowerCase();if(t.includes('plc')&&t.includes('cpu'))return'plc';if(t.includes('i/o'))return'io';if(t.includes('безопас')||t.includes('בטיחות')||t.includes('safety'))return'safety';if(t.includes('24v'))return'power';if(t.includes('ethernet')||t.includes('связ')||t.includes('תקשורת')||t.includes('communication'))return'ethernet';if(t.includes('глав')||t.includes('ראשית')||t.includes('main supply'))return'breakers';if(t.includes('контакт')||t.includes('קונטקט')||t.includes('contactor'))return'contactors';if(t.includes('реле')||t.includes('ממסר')||t.includes('relay'))return'relays';if(t.includes('автомат')||t.includes('предохран')||t.includes('מאמ')||t.includes('נתיך')||t.includes('breaker')||t.includes('fuse'))return'breakers';if(t.includes('датчик')||t.includes('энкод')||t.includes('חייש')||t.includes('אנקוד')||t.includes('sensor')||t.includes('encoder'))return'sensors';if(t.includes('сигнал')||t.includes('кноп')||t.includes('איתות')||t.includes('לחצן')||t.includes('signal'))return'signals';if(t.includes('привод')||t.includes('דרייב')||t.includes('drive')||t.includes('inverter'))return'drives';if(t.includes('мотор')||t.includes('מנוע')||t.includes('motor'))return'motors';if(t.includes('вент')||t.includes('מאוורר')||t.includes('fan'))return'fans';if(t.includes('гидр')||t.includes('הידרא')||t.includes('hydraulic'))return'hydraulics';if(t.includes('управ')||t.includes('בקרה')||t.includes('control'))return'control';return''}
 function bindSection(){if(!isE4())return;let box=document.getElementById('e4DrawingGroups');if(!box)return;let sk=sectionKey(),src=data[sk]||{};box.querySelectorAll('.e4draw-card').forEach(c=>{c.onclick=null;if(c.dataset.e4bound)return;c.dataset.e4bound='1';c.addEventListener('click',function(ev){ev.preventDefault();ev.stopImmediatePropagation();let title=(c.querySelector('b')||{}).textContent||'',k=classifyTitle(title),rows=src[k]||[];show(title,rows.length?rows:[{ru:'Позиции из чертежа ещё не перенесены в этот раздел',he:'הפריטים מהשרטוט עדיין לא הועברו לסעיף זה',en:'Drawing items are not yet transferred to this section',d:'',model:'',spec:'',qty:0}],box)},true)})}
 function addMainCards(box){let g=box.querySelector('.e4draw-grid');if(!g)return;let extra=[['contactors','Контакторы','קונטקטורים','Contactors'],['relays','Реле','ממסרים','Relays'],['breakers','Автоматы / предохранители','מאמ״תים / נתיכים','Breakers / fuses'],['sensors','Датчики / энкодеры','חיישנים / אנקודרים','Sensors / encoders'],['signals','Кнопки / сигнализация','לחצנים / איתות','Pushbuttons / signals']];extra.forEach(x=>{if(g.querySelector('[data-e4key="'+x[0]+'"]'))return;let c=document.createElement('div');c.className='e4draw-card';c.dataset.e4key=x[0];c.innerHTML='<b>'+e(lang==='he'?x[2]:lang==='en'?x[3]:x[1])+'</b><span>'+tx('Оборудование из электрической схемы','ציוד מתוך שרטוט החשמל','Equipment from electrical drawing')+'</span>';g.appendChild(c)})}
 function bindMain(){if(!isE4())return;let box=document.getElementById('e4MainGroups');if(!box)return;addMainCards(box);box.querySelectorAll('.e4draw-card').forEach(c=>{c.onclick=null;if(c.dataset.e4boundMain)return;c.dataset.e4boundMain='1';c.addEventListener('click',function(ev){ev.preventDefault();ev.stopImmediatePropagation();let title=(c.querySelector('b')||{}).textContent||'',k=c.dataset.e4key||classifyTitle(title),rows=data.main[k]||[];show(title,rows.length?rows:[{ru:'Раздел открыт. Позиции из чертежа будут добавляться сюда.',he:'הסעיף פתוח. פריטים מהשרטוט יתווספו לכאן.',en:'Section is open. Drawing items will be added here.',d:'',model:'',spec:'',qty:0}],box)},true)})}
 const oe=window.openExtruderSection;window.openExtruderSection=function(i){oe(i);setTimeout(bindSection,100)};
 const om=window.openExtruderMainPanel;if(om)window.openExtruderMainPanel=function(){om();setTimeout(bindMain,120)};
 document.addEventListener('click',()=>setTimeout(()=>{bindSection();bindMain()},30));document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{bindSection();bindMain()},100)));
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
