def apply(legacy):
    patch = r'''<style>
/* Extruder 4 station pages use the same two-level navigation as the main cabinet. */
#extruderSectionPage #extruderPartsInline,
#extruderSectionPage #extruderSectionPanelBlock,
#extruderSectionPage .e4detailbox{display:none!important}
#e4StationCatalog{margin:14px 0 20px;padding:15px;border:1px solid #d3ddde;border-radius:14px;background:#fff}
#e4StationCatalog h2{margin:0 0 14px;font-size:20px}.e4st-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px}.e4st-tile{min-height:72px;border:1px solid #cbd8d9;border-radius:11px;background:#f8fbfa;color:#34454b;font-size:15px;font-weight:700;padding:12px;cursor:pointer}.e4st-tile:hover{background:#eef5f3;border-color:#91aaad}.e4st-detail{margin-top:14px;border:1px solid #cbd8d9;border-radius:12px;padding:14px}.e4st-wrap{overflow:auto;max-height:580px}.e4st-table{width:100%;border-collapse:collapse;min-width:900px}.e4st-table th,.e4st-table td{padding:8px;border-bottom:1px solid #e3eaea;text-align:left;font-size:12px;vertical-align:top}.e4st-table th{position:sticky;top:0;background:#f4f8f7}.e4st-head{display:flex;justify-content:space-between;align-items:center}.e4st-back{padding:7px 11px;border:1px solid #cbd8d9;border-radius:8px;background:#f4f8f7;cursor:pointer}@media(max-width:850px){.e4st-grid{grid-template-columns:repeat(2,minmax(140px,1fr))}}
</style><script>
(function(){
 function tx(a,b,c){return lang==='he'?b:lang==='en'?c:a}
 function x(s){return String(s??'').replace(/[&<>\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]})}
 function isE4(){var n=((machines[lang]||[])[currentMachineIndex]||'').toLowerCase();return n.indexOf('4')>=0&&(n.indexOf('экструдер')>=0||n.indexOf('אקסטרודר')>=0||n.indexOf('extruder')>=0)}
 function sname(){return ((extruderSections[lang]||[])[currentExtruderSection]||'')}
 function skey(){var s=sname().toLowerCase();if(s.indexOf('доз')>=0||s.indexOf('מינון')>=0||s.indexOf('dos')>=0)return'dosing';if((s.indexOf('extruder a')>=0)||(s.indexOf('экструдер a')>=0)||(s.indexOf('אקסטרודר a')>=0)||(s.indexOf('משני')>=0))return'a';if((s.indexOf('extruder b')>=0)||(s.indexOf('экструдер b')>=0)||(s.indexOf('אקסטרודר b')>=0)||(s.indexOf('ראשי')>=0))return'b';if(s.indexOf('cal')>=0||s.indexOf('кал')>=0||s.indexOf('קלנ')>=0)return'calender';if(s.indexOf('sil')>=0||s.indexOf('силик')>=0||s.indexOf('סיליק')>=0)return'silicone';if(s.indexOf('receiv')>=0||s.indexOf('прием')>=0||s.indexOf('קולט')>=0)return'receiver';if(s.indexOf('wind')>=0||s.indexOf('намот')>=0||s.indexOf('גליל')>=0)return'winding';return'other'}
 var baseCats=[
 ['drives',['Драйверы','דרייבים','Drives']],['motors',['Моторы','מנועים','Motors']],['starters',['Пускатели / защита','מתנעים / הגנה','Starters / protection']],['contactors',['Контакторы','קונטקטורים','Contactors']],['relays',['Реле','ממסרים','Relays']],['sensors',['Датчики','חיישנים','Sensors']],['control',['Управление / I/O','בקרה / I/O','Control / I/O']],['valves',['Клапаны / пневматика','שסתומים / פנאומטיקה','Valves / pneumatics']],['heating',['Нагрев','חימום','Heating']],['other',['Прочее','אחר','Other']]
 ];
 var seed={
  a:{drives:[['Привод экструдера A','-53U1','ABB','ACS 800-01-0100-3','75 kW · Profibus ADD=21'],['Привод объёмного насоса A','-38U1','ABB','ACS 800-01-0006-3','3.9 kW · Profibus ADD=26']],motors:[['Мотор экструдера A','-53M1','ABB','M3AA 250 SMB','75 kW'],['Мотор объёмного насоса A','-38M1','LENZE','MCA 14L35','3.9 kW']]},
  b:{drives:[['Привод экструдера B','-61U1','ABB','ACS 800-04-0400-3','315 kW · Profibus ADD=11'],['Привод объёмного насоса B','-43U1','ABB','ACS 800-01-0030-3','20.3 kW · Profibus ADD=16']],motors:[['Мотор экструдера B','-61M1','ABB','M2BA 355 SMA4','315 kW'],['Мотор объёмного насоса B','-43M1','LENZE','MCA 21X35','20.3 kW']]},
  calender:{drives:[['Привод входного валка','-91U1','ABB','ACS 800-01-0011-3','6.5 kW · ADD=70'],['Привод центрального валка','-95U1','ABB','ACS 800-01-0020-3','12 kW · ADD=71'],['Привод выходного валка','-99U1','ABB','ACS 800-01-0011-3','6.5 kW · ADD=72'],['Привод перемещения каландра','-110U1','ABB','ACS 550-01-03A3-4J-404','0.25 kW'],['Привод охлаждающего валка','-120U1','ABB','ACS 800-01-0006-3','4.0 kW · ADD=73'],['Привод тянущего устройства','-130U1','ABB','ACS 800-01-0005-3','2.7 kW · ADD=81'],['Привод прижимного валка','-145U1','ABB','ACS 550-01-03A3-4J-404','0.25 kW · ADD=75']],motors:[['Мотор входного валка','-91M1','','AX 100K.2','6.5 kW'],['Мотор центрального валка','-95M1','','AX 100K.4','12 kW'],['Мотор выходного валка','-99M1','','AX 100K.2','6.5 kW'],['Мотор охлаждающего валка','-120M1','','AX 80CS.2',''],['Мотор тянущего устройства','-130M1','','AX 80CS.075','2.7 kW']]}
 };
 function userRows(){try{var d=JSON.parse(localStorage.getItem('machine_parts_v1')||'{}');return d['extruder:'+currentMachineIndex+':'+currentExtruderSection]||[]}catch(e){return[]}}
 function classify(r){var s=((r.model||'')+' '+(r.mfr||'')+' '+(r.specs||'')+' '+(r.notes||'')).toLowerCase();if(/acs|drive|inverter|vfd|דרייב|инвер/.test(s))return'drives';if(/motor|мотор|מנוע/.test(s))return'motors';if(/3ra|starter|пуск|מתנע/.test(s))return'starters';if(/3rt|3rh|contactor|контактор|קונטקט/.test(s))return'contactors';if(/relay|реле|ממסר|ka\b/.test(s))return'relays';if(/sensor|датчик|חיישן|encoder|энкод/.test(s))return'sensors';if(/plc|i\/o|module|модул|בקר|cpu/.test(s))return'control';if(/valve|solenoid|pneum|клап|пневм|שסתום/.test(s))return'valves';if(/heater|heat|нагрев|חימום|resist/.test(s))return'heating';return'other'}
 function rowsFor(cat){var out=[];var fixed=(seed[skey()]||{})[cat]||[];fixed.forEach(function(r){out.push(r)});userRows().forEach(function(r){if(classify(r)===cat)out.push([r.model||r.code||'',r.drawingNo||r.code||'',r.mfr||'',r.model||'',r.specs||''])});return out}
 function ct(c){return c[1][lang==='he'?1:lang==='en'?2:0]}
 var selected=null;
 function render(){if(!isE4())return;var p=document.getElementById('extruderSectionPage');if(!p||!p.classList.contains('active'))return;var old=document.getElementById('e4StationCatalog');if(old)old.remove();var d=document.createElement('div');d.id='e4StationCatalog';if(selected){var c=baseCats.find(function(z){return z[0]===selected});var rows=rowsFor(selected);d.innerHTML='<h2>'+x(sname())+'</h2><div class="e4st-detail"><div class="e4st-head"><h3>'+x(ct(c))+'</h3><button type="button" class="e4st-back" id="e4StationBack">'+tx('Назад','חזור','Back')+'</button></div><div class="e4st-wrap"><table class="e4st-table"><thead><tr><th>'+tx('Название','שם','Name')+'</th><th>'+tx('Номер на чертеже','מספר בשרטוט','Drawing designation')+'</th><th>'+tx('Производитель','יצרן','Manufacturer')+'</th><th>Part No. / '+tx('модель','דגם','model')+'</th><th>'+tx('Данные','נתונים','Data')+'</th></tr></thead><tbody>'+(rows.length?rows.map(function(r){return '<tr>'+r.map(function(v){return '<td>'+x(v)+'</td>'}).join('')+'</tr>'}).join(''):'<tr><td colspan="5">'+tx('Пока нет подтверждённых позиций из чертежей.','עדיין אין פריטים מאומתים מהשרטוטים.','No verified drawing items yet.')+'</td></tr>')+'</tbody></table></div></div>';p.appendChild(d);document.getElementById('e4StationBack').onclick=function(ev){ev.stopPropagation();selected=null;render()};return}
 d.innerHTML='<h2>'+x(sname())+'</h2><div class="e4st-grid">'+baseCats.map(function(c){return '<button type="button" class="e4st-tile" data-e4st="'+c[0]+'">'+x(ct(c))+'</button>'}).join('')+'</div>';p.appendChild(d);d.querySelectorAll('[data-e4st]').forEach(function(b){b.onclick=function(ev){ev.stopPropagation();selected=this.getAttribute('data-e4st');render()}})
 }
 var old=window.openExtruderSection;if(typeof old==='function'&&!old.__e4stations){window.openExtruderSection=function(i){selected=null;var r=old.apply(this,arguments);setTimeout(render,60);setTimeout(render,220);return r};window.openExtruderSection.__e4stations=true}
 document.querySelectorAll('.lang button').forEach(function(b){b.addEventListener('click',function(){setTimeout(render,80)})});
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
