def apply(legacy):
    patch = r'''<style>
.machine-parts-add{display:inline-block;margin:12px 0;padding:10px 15px;border:0;border-radius:9px;background:#527d83;color:#fff;font-weight:700;cursor:pointer}.machine-parts-wrap{overflow:auto;border:1px solid #ccd7d8;border-radius:10px;background:#fff;margin-top:10px}.machine-parts-wrap table{min-width:860px}.machine-parts-actions button{padding:4px 7px;cursor:pointer}.machine-parts-empty{padding:18px;color:#718087}.machine-parts-link{margin-top:14px;min-height:68px}.machine-parts-modal label{display:block;font-weight:700;margin:10px 0 4px}.machine-parts-modal input,.machine-parts-modal textarea{width:100%;padding:10px;border:1px solid #ccd7d8;border-radius:8px;background:#fbfdfc}.machine-parts-modal textarea{min-height:70px}.mp-inline{margin-top:16px;padding:14px;border:1px solid #ccd7d8;border-radius:12px;background:#fff}.mp-match{margin-top:8px;padding:9px 10px;border-radius:8px;background:#eef5f3;font-size:13px;line-height:1.4}.mp-match:empty{display:none}.mp-dup{background:#fff2e8}
</style>
<div class="page" id="machinePartsPage"><button class="back" id="machinePartsBack"></button><h2 id="machinePartsTitle"></h2><button class="machine-parts-add" id="machinePartsAdd" onclick="openMachinePartEdit(-1)"></button><div class="machine-parts-wrap"><table><thead><tr><th id="mpThCode"></th><th id="mpThModel"></th><th id="mpThMfr"></th><th id="mpThSpecs"></th><th id="mpThQty"></th><th id="mpThPrice"></th><th id="mpThNotes"></th><th id="mpThEdit"></th></tr></thead><tbody id="machinePartsBody"></tbody></table></div></div>
<div class="modal" id="machinePartModal"><div class="modal-card machine-parts-modal"><h3 id="machinePartModalTitle"></h3><label id="mpLCode"></label><input id="mpCode"><label id="mpLModel"></label><input id="mpModel"><div id="mpMatch" class="mp-match"></div><label id="mpLMfr"></label><input id="mpMfr"><label id="mpLSpecs"></label><textarea id="mpSpecs"></textarea><label id="mpLQty"></label><input id="mpQty" type="number" min="0" step="1"><label id="mpLPrice"></label><input id="mpPrice" type="number" step="0.01"><label id="mpLNotes"></label><textarea id="mpNotes"></textarea><div class="modal-actions"><button class="modal-btn" id="mpCancel" onclick="closeMachinePartEdit()"></button><button class="modal-btn primary" id="mpSave" onclick="saveMachinePart()"></button></div></div></div>
<script>
(function(){
 const KEY='machine_parts_v1';
 let ctx=null,editIndex=-1;
 function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
 function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
 function tx(ru,he,en){return lang==='he'?he:lang==='en'?en:ru}
 function e(s){return esc(String(s??''))}
 function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,'')}
 function machineNameByIndex(i){return (machines[lang]&&machines[lang][i])||''}
 function machineName(){return machineNameByIndex(currentMachineIndex)}
 function ctxTitle(c){c=c||ctx;if(!c)return'';if(c.type==='thermo')return machineNameByIndex(c.machine)+' — '+thermoSections[lang][c.section];if(c.type==='extruder')return machineNameByIndex(c.machine)+' — '+extruderSections[lang][c.section];return machineNameByIndex(c.machine)}
 function keyFor(c){return c.type+':'+c.machine+(c.section===null?'':':'+c.section)}
 function contextNow(type){if(type==='thermo')return{type:'thermo',machine:currentMachineIndex,section:currentThermoSection};if(type==='extruder')return{type:'extruder',machine:currentMachineIndex,section:currentExtruderSection};return{type:'machine',machine:currentMachineIndex,section:null}}
 function items(c){let d=load();return d[keyFor(c||ctx)]||[]}
 function store(a,c){let d=load();d[keyFor(c||ctx)]=a;save(d)}
 function syncText(){if(!ctx)return;machinePartsTitle.textContent=ctxTitle()+' — '+tx('Электрические части','חלקי חשמל','Electrical parts');machinePartsAdd.textContent=tx('+ Новая позиция','+ פריט חדש','+ New item');machinePartsBack.textContent=tx('← Назад','← חזרה','← Back');mpThCode.textContent=tx('Код','קוד','Code');mpThModel.textContent=tx('Модель / артикул','דגם / מק״ט','Model / part no.');mpThMfr.textContent=tx('Фирма','יצרן','Manufacturer');mpThSpecs.textContent=tx('Параметры','נתונים','Specifications');mpThQty.textContent=tx('Количество','כמות','Quantity');mpThPrice.textContent=tx('Цена','מחיר','Price');mpThNotes.textContent=tx('Примечание','הערה','Notes');mpThEdit.textContent=tx('Изменение','עריכה','Edit');mpLCode.textContent=tx('Код склада / внутренний код','קוד מחסן / קוד פנימי','Warehouse / internal code');mpLModel.textContent=tx('Модель / артикул','דגם / מק״ט','Model / part no.');mpLMfr.textContent=tx('Фирма','יצרן','Manufacturer');mpLSpecs.textContent=tx('Параметры','נתונים','Specifications');mpLQty.textContent=tx('Количество на этом узле','כמות ביחידה הזאת','Quantity on this section');mpLPrice.textContent=tx('Цена','מחיר','Price');mpLNotes.textContent=tx('Примечание','הערה','Notes');mpCancel.textContent=tx('Отмена','ביטול','Cancel');mpSave.textContent=tx('Сохранить','שמור','Save')}
 function tableHtml(c){let a=items(c);return `<div class="machine-parts-wrap"><table><thead><tr><th>${tx('Код','קוד','Code')}</th><th>${tx('Модель / артикул','דגם / מק״ט','Model / part no.')}</th><th>${tx('Фирма','יצרן','Manufacturer')}</th><th>${tx('Параметры','נתונים','Specifications')}</th><th>${tx('Количество','כמות','Quantity')}</th><th>${tx('Цена','מחיר','Price')}</th><th>${tx('Примечание','הערה','Notes')}</th><th>${tx('Изменение','עריכה','Edit')}</th></tr></thead><tbody>${a.length?a.map((x,i)=>`<tr><td><b>${e(x.code)}</b></td><td>${e(x.model)}</td><td>${e(x.mfr)}</td><td>${e(x.specs)}</td><td class="qty">${e(x.qty)}</td><td>${x.price!==''?e(x.price):''}</td><td>${e(x.notes)}</td><td class="machine-parts-actions"><button onclick="openMachinePartEditInline('${c.type}',${c.machine},${c.section===null?'null':c.section},${i})">✎</button></td></tr>`).join(''):`<tr><td colspan="8" class="machine-parts-empty">${tx('Пока ничего не добавлено','עדיין לא נוסף דבר','Nothing added yet')}</td></tr>`}</tbody></table></div>`}
 window.renderMachineParts=function(){if(!ctx)return;syncText();machinePartsBody.innerHTML=items().length?items().map((x,i)=>`<tr><td><b>${e(x.code)}</b></td><td>${e(x.model)}</td><td>${e(x.mfr)}</td><td>${e(x.specs)}</td><td class="qty">${e(x.qty)}</td><td>${x.price!==''?e(x.price):''}</td><td>${e(x.notes)}</td><td class="machine-parts-actions"><button onclick="openMachinePartEdit(${i})">✎</button></td></tr>`).join(''):`<tr><td colspan="8" class="machine-parts-empty">${tx('Пока ничего не добавлено','עדיין לא נוסף דבר','Nothing added yet')}</td></tr>`}
 function renderInline(){let host=null,c=null;if(document.getElementById('thermoSectionPage').classList.contains('active')&&currentThermoSection!==null){host=document.getElementById('thermoPartsInline');c=contextNow('thermo')}else if(document.getElementById('extruderSectionPage').classList.contains('active')&&currentExtruderSection!==null){host=document.getElementById('extruderPartsInline');c=contextNow('extruder')}else if(document.getElementById('machineDetail').classList.contains('active')&&currentMachineIndex!==null){host=document.getElementById('genericPartsInline');c=contextNow('machine')}if(!host||!c)return;host.innerHTML=`<button class="machine-parts-add" onclick="openMachinePartEditInline('${c.type}',${c.machine},${c.section===null?'null':c.section},-1)">${tx('+ Новая позиция','+ פריט חדש','+ New item')}</button>${tableHtml(c)}`}
 window.openMachineParts=function(type){ctx=contextNow(type);machinePartsBack.onclick=function(){if(ctx.type==='thermo')openThermoSection(ctx.section);else if(ctx.type==='extruder')openExtruderSection(ctx.section);else showPage('machineDetail')};renderMachineParts();showPage('machinePartsPage')}
 function findMatches(){let q=norm(mpModel.value),code=norm(mpCode.value);if(q.length<3&&code.length<2){mpMatch.textContent='';mpMatch.classList.remove('mp-dup');return}let messages=[];let wh=inventory.filter(x=>(q&&norm(x.name)===q)||(code&&norm(x.internalCode)===code));if(wh.length){messages.push(tx('На главном складе: ','במחסן הראשי: ','Main warehouse: ')+wh.map(x=>`${x.name} — ${x.qty??0}`).join('; '))}let d=load(),other=[];Object.keys(d).forEach(k=>(d[k]||[]).forEach(x=>{if((q&&norm(x.model)===q)||(code&&norm(x.code)===code))other.push({k,x})}));if(other.length){messages.push(tx('На машинах: ','במכונות: ','On machines: ')+other.map(o=>`${o.x.model} × ${o.x.qty}`).join('; '))}let same=items().some((x,i)=>i!==editIndex&&((q&&norm(x.model)===q)||(code&&norm(x.code)===code)));mpMatch.textContent=messages.join(' | ')+(same?(messages.length?' | ':'')+tx('Эта позиция уже есть в этой таблице.','הפריט כבר קיים בטבלה הזאת.','This item already exists in this table.'): '');mpMatch.classList.toggle('mp-dup',same)}
 window.openMachinePartEdit=function(i){editIndex=i;let a=items(),x=i>=0?a[i]:{code:'',model:'',mfr:'',specs:'',qty:1,price:'',notes:''};machinePartModalTitle.textContent=tx('Позиция оборудования','פריט ציוד','Equipment item');mpCode.value=x.code||'';mpModel.value=x.model||'';mpMfr.value=x.mfr||'';mpSpecs.value=x.specs||'';mpQty.value=x.qty??1;mpPrice.value=x.price??'';mpNotes.value=x.notes||'';syncText();findMatches();machinePartModal.classList.add('open')}
 window.openMachinePartEditInline=function(type,machine,section,i){ctx={type,machine,section};openMachinePartEdit(i)}
 window.closeMachinePartEdit=function(){machinePartModal.classList.remove('open')}
 window.saveMachinePart=function(){let model=mpModel.value.trim(),code=mpCode.value.trim();if(!model)return;let a=items(),nmodel=norm(model),ncode=norm(code),dup=a.findIndex((x,i)=>i!==editIndex&&((nmodel&&norm(x.model)===nmodel)||(ncode&&norm(x.code)===ncode)));if(dup>=0){alert(tx('Эта позиция уже есть в этой таблице. Дубликат не добавлен.','הפריט כבר קיים בטבלה הזאת. לא נוסף כפול.','This item already exists in this table. Duplicate was not added.'));return}let x={code,model,mfr:mpMfr.value.trim(),specs:mpSpecs.value.trim(),qty:Math.max(0,Number(mpQty.value)||0),price:mpPrice.value===''?'':Number(mpPrice.value),notes:mpNotes.value.trim()};if(editIndex>=0)a[editIndex]=x;else a.push(x);store(a);closeMachinePartEdit();renderMachineParts();renderInline()}
 mpModel.addEventListener('input',findMatches);mpCode.addEventListener('input',findMatches);mpMfr.addEventListener('input',findMatches);

 function addInline(id,page){if(page&&!document.getElementById(id)){let d=document.createElement('div');d.id=id;d.className='mp-inline';page.appendChild(d)}}
 addInline('thermoPartsInline',document.getElementById('thermoSectionPage'));addInline('extruderPartsInline',document.getElementById('extruderSectionPage'));addInline('genericPartsInline',document.getElementById('machineDetail'));
 const oldThermo=window.openThermoSection;window.openThermoSection=function(i){oldThermo(i);setTimeout(renderInline,0)};
 const oldExtr=window.openExtruderSection;window.openExtruderSection=function(i){oldExtr(i);setTimeout(renderInline,0)};
 const oldMachine=window.openMachine;window.openMachine=function(i){oldMachine(i);setTimeout(renderInline,0)};
 document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{if(document.getElementById('machinePartsPage').classList.contains('active'))renderMachineParts();renderInline()},0)));

 // Warehouse duplicate protection: do not create a second identical stock position in the same category.
 const baseSaveWarehouseItem=window.saveWarehouseItem;
 window.saveWarehouseItem=function(){if(currentWarehouseEditIndex<0){let model=wiModel.value.trim(),code=(document.getElementById('wiInternalCode')||{}).value||'',mfr=wiManufacturer.value.trim(),nm=norm(model),nc=norm(code),nf=norm(mfr);let dup=inventory.find(x=>x.cat===currentWarehouseCat&&((nc&&norm(x.internalCode)===nc)||(nm&&norm(x.name)===nm&&(!nf||norm(x.manufacturer)===nf))));if(dup){alert(tx('Такая позиция уже есть в этой таблице. Сейчас на складе: ','הפריט כבר קיים בטבלה הזאת. כמות במחסן: ','This item already exists in this table. Warehouse quantity: ')+(dup.qty??0));return}}baseSaveWarehouseItem()}

 renderInline();
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
