def apply(legacy):
    patch = r'''<style>
.search-center{display:grid;gap:14px}.search-card{border:1px solid #ccd7d8;border-radius:12px;background:#fff;padding:16px}.search-card h3{margin:0 0 9px}.search-row{display:flex;gap:8px;flex-wrap:wrap}.search-row input{flex:1;min-width:220px;padding:11px;border:1px solid #ccd7d8;border-radius:8px}.search-go{padding:10px 15px;border:0;border-radius:8px;background:#527d83;color:#fff;font-weight:700;cursor:pointer}.search-results{margin-top:10px;display:grid;gap:8px}.search-hit{padding:10px;border:1px solid #dbe4e4;border-radius:9px;background:#f8fbfa}.search-hit button{margin-top:7px}.search-empty{color:#718087;padding:8px 0}.search-diamond{display:block}
</style>
<button class="diamond-button search-diamond" id="searchBtn" onclick="openSearchCenter()"><div class="diamond"><div class="diamond-inner"><span class="icon">🔎</span><span id="searchNav"></span></div></div></button>
<div class="page" id="searchPage"><h2 id="searchTitle"></h2><p class="subtitle" id="searchSub"></p><div class="search-center">
<div class="search-card"><h3 id="searchWhTitle"></h3><div class="search-row"><input id="searchWhInput"><button class="search-go" id="searchWhGo" onclick="searchWarehouseGlobal()"></button></div><div class="search-results" id="searchWhResults"></div></div>
<div class="search-card"><h3 id="searchWebTitle"></h3><div class="search-row"><input id="searchWebInput"><button class="search-go" id="searchWebGo" onclick="searchInternetPart()"></button></div><div class="search-results" id="searchWebResults"></div></div>
<div class="search-card"><h3 id="searchMachineTitle"></h3><div class="search-row"><input id="searchMachineInput"><button class="search-go" id="searchMachineGo" onclick="searchMachinesGlobal()"></button></div><div class="search-results" id="searchMachineResults"></div></div>
</div></div>
<script>
(function(){
 const KEY='machine_parts_v1';
 function tx(ru,he,en){return lang==='he'?he:lang==='en'?en:ru}
 function e(s){return esc(String(s??''))}
 function norm(s){return String(s||'').toLowerCase().replace(/[\s._\-/]+/g,'')}
 function contains(x,q){return norm(x).includes(norm(q))}
 function loadParts(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return{}}}
 function machineName(i){return (machines[lang]&&machines[lang][Number(i)])||tx('Машина ','מכונה ','Machine ')+i}
 function sectionLabel(type,i){if(i===undefined||i===null||i==='')return'';if(type==='extruder'&&extruderSections[lang])return extruderSections[lang][Number(i)]||'';if(type==='thermo'&&thermoSections[lang])return thermoSections[lang][Number(i)]||'';return''}
 function whereKey(k){let p=k.split(':');if(p[0]==='maincab'||p[0]==='panel-main')return machineName(p[1])+' — '+tx('Главный электрощит','לוח חשמל ראשי','Main electrical cabinet');if(p[0]==='panel-section')return machineName(p[1])+' — '+tx('Электрощит','לוח חשמל','Electrical cabinet')+' — '+sectionLabel('extruder',p[2]);if(p[0]==='extruder')return machineName(p[1])+' — '+sectionLabel('extruder',p[2]);if(p[0]==='thermo')return machineName(p[1])+' — '+sectionLabel('thermo',p[2]);if(p[0]==='machine')return machineName(p[1]);return k}
 function sync(){searchNav.textContent=tx('Поиск','חיפוש','Search');searchTitle.textContent=tx('Поиск','חיפוש','Search');searchSub.textContent=tx('Склад, интернет и установленные детали на машинах','מחסן, אינטרנט וחלקים המותקנים במכונות','Warehouse, internet and parts installed on machines');searchWhTitle.textContent=tx('Поиск в главном складе','חיפוש במחסן הראשי','Search main warehouse');searchWebTitle.textContent=tx('Поиск в интернете','חיפוש באינטרנט','Internet search');searchMachineTitle.textContent=tx('Поиск по машинам','חיפוש במכונות','Search machines');[searchWhGo,searchWebGo,searchMachineGo].forEach(x=>x.textContent=tx('Искать','חפש','Search'));searchWhInput.placeholder=tx('Модель, номер, фирма, параметры...','דגם, מק״ט, יצרן, נתונים...','Model, part no., manufacturer, specs...');searchWebInput.placeholder=tx('Точная модель или номер детали','דגם מדויק או מק״ט','Exact model or part number');searchMachineInput.placeholder=tx('Модель, номер или название детали','דגם, מק״ט או שם החלק','Model, part no. or part name')}
 window.openSearchCenter=function(){sync();showPage('searchPage')}
 window.searchWarehouseGlobal=function(){let q=searchWhInput.value.trim();if(!q){searchWhResults.innerHTML='';return}let hits=inventory.map((x,i)=>({x,i})).filter(o=>[o.x.internalCode,o.x.name,o.x.manufacturer,o.x.specs,o.x.machine,o.x.notes].some(v=>contains(v,q)));if(!hits.length){searchWhResults.innerHTML=`<div class="search-empty">${tx('Не найдено на складе.','לא נמצא במחסן.','Not found in warehouse.')}</div>`;return}searchWhResults.innerHTML=hits.slice(0,50).map(o=>{let cat=(categoryLabels[o.x.cat]||{})[lang]||o.x.cat;return `<div class="search-hit"><b>${e(o.x.name)}</b> — ${e(o.x.manufacturer)}<br>${tx('Количество','כמות','Quantity')}: <b>${e(o.x.qty??0)}</b> · ${tx('Таблица','טבלה','Table')}: <b>${e(cat)}</b><br><button class="small-btn" onclick="goWarehouseHit('${e(o.x.cat)}','${o.i}')">${tx('Открыть место','פתח מיקום','Open location')}</button></div>`}).join('')}
 window.goWarehouseHit=function(cat,i){openWarehouseCategory(cat);setTimeout(()=>{warehouseSearch.value=inventory[Number(i)]?.name||'';renderWarehouseItems()},0)}
 window.searchInternetPart=function(){let q=searchWebInput.value.trim();if(!q){searchWebResults.innerHTML='';return}let exact=encodeURIComponent('"'+q+'" datasheet manual manufacturer');let buy=encodeURIComponent('"'+q+'" distributor Israel');searchWebResults.innerHTML=`<div class="search-hit">${tx('Открою технический поиск по точной модели: datasheet, manual, производитель и описание работы.','חיפוש טכני לפי הדגם המדויק: datasheet, manual, יצרן והסבר פעולה.','Technical search by exact model: datasheet, manual, manufacturer and operating information.')}<br><button class="small-btn" onclick="window.open('https://www.google.com/search?q=${exact}','_blank')">${tx('Документация / как работает','תיעוד / איך עובד','Documentation / how it works')}</button> <button class="small-btn" onclick="window.open('https://www.google.com/search?q=${buy}','_blank')">${tx('Где купить / поставщики','איפה לקנות / ספקים','Where to buy / suppliers')}</button></div>`}
 window.searchMachinesGlobal=function(){let q=searchMachineInput.value.trim();if(!q){searchMachineResults.innerHTML='';return}let d=loadParts(),hits=[];Object.keys(d).forEach(k=>(d[k]||[]).forEach(x=>{if([x.code,x.model,x.mfr,x.specs,x.notes].some(v=>contains(v,q)))hits.push({k,x})}));if(!hits.length){searchMachineResults.innerHTML=`<div class="search-empty">${tx('На машинах не найдено.','לא נמצא במכונות.','Not found on machines.')}</div>`;return}searchMachineResults.innerHTML=hits.slice(0,100).map(o=>`<div class="search-hit"><b>${e(o.x.model||o.x.code)}</b> — ${e(o.x.mfr||'')}<br>${tx('Где стоит','איפה מותקן','Installed at')}: <b>${e(whereKey(o.k))}</b> · ${tx('Количество','כמות','Quantity')}: ${e(o.x.qty??0)}</div>`).join('')}
 ;['searchWhInput','searchWebInput','searchMachineInput'].forEach((id,n)=>document.getElementById(id).addEventListener('keydown',ev=>{if(ev.key==='Enter')[searchWarehouseGlobal,searchInternetPart,searchMachinesGlobal][n]()}));
 let side=document.querySelector('.side');if(side){let b=document.getElementById('searchBtn');side.appendChild(b)}
 document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',()=>setTimeout(sync,0)));sync();
})();
</script>'''
    legacy.HTML = legacy.HTML.replace('</body>', patch + '</body>')
